module.exports = {
  id: 1,
  ageRestricted: false,
  type: 'TV Series',
  episodeCount: 13,
  startDate: '1999-01-03',
  endDate: '1999-03-28',
  titles: [
    { title: 'Seikai no Monshou', language: 'x-jat', type: 'main' },
    { title: 'Hvězdný erb', language: 'cs', type: 'synonym' },
    { title: '星界之纹章', language: 'zh-Hans', type: 'synonym' },
    { title: 'CotS', language: 'en', type: 'short' },
    { title: 'SnM', language: 'x-jat', type: 'short' },
    { title: '星界の紋章', language: 'ja', type: 'official' },
    { title: 'Crest of the Stars', language: 'en', type: 'official' },
    { title: 'Crest of the Stars', language: 'fr', type: 'official' },
    { title: 'Crest of the Stars', language: 'pl', type: 'official' },
  ],
  description:
    '* Based on the sci-fi novel series by http://anidb.net/cr4495 [Morioka Hiroyuki].\nhttp://anidb.net/ch4081 [Linn Jinto]`s life changes forever when the http://anidb.net/ch7514 [Humankind Empire Abh] takes over his home planet of Martine without firing a single shot. He is soon sent off to study the http://anidb.net/t2324 [Abh] language and culture and to prepare himself for his future as a nobleman — a future he never dreamed of, asked for, or even wanted.\nNow, Jinto is entering the next phase of his training, and he is about to meet the first Abh in his life, the lovely http://anidb.net/ch28 [Lafiel]. However, Jinto is about to learn that there is more to her than meets the eye, and together they will have to fight for their very lives.',
  picture: '440.jpg',
  ratings: {
    permanent: { score: '8.16', count: '4427' },
    temporary: { score: '8.23', count: '4457' },
    review: { score: '8.70', count: '12' },
  },
  related: [
    { id: 4, type: 'Sequel', name: 'Seikai no Senki' },
    { id: 6, type: 'Prequel', name: 'Seikai no Danshou: Tanjou' },
    { id: 1623, type: 'Summary', name: 'Seikai no Monshou Tokubetsu Hen' },
  ],
  similar: [
    {
      id: 584, approval: 74, total: 88, name: 'Ginga Eiyuu Densetsu',
    },
    {
      id: 2745, approval: 52, total: 62, name: 'Starship Operators',
    },
    {
      id: 6005, approval: 36, total: 52, name: 'Tytania',
    },
    {
      id: 192, approval: 18, total: 40, name: 'Mugen no Ryvius',
    },
    {
      id: 630, approval: 14, total: 28, name: 'Uchuu no Stellvia',
    },
    {
      id: 5406, approval: 3, total: 16, name: 'Ookami to Koushinryou',
    },
    {
      id: 18, approval: 2, total: 11, name: 'Musekinin Kanchou Tylor',
    },
  ],
  recommendations: [
    {
      type: 'Recommended',
      uid: 567190,
      content:
        'As has been said, a solid space opera, but where it really shines is the two protagonists and how they interact. They have misunderstandings constantly, but they just talk it out until they come to a better understanding of each other. It`s beautiful.\n\nThe series does have its issues. The art style and animation are fine despite the age, but the direction and editing are incredibly shoddy at times and the pacing is off where subplots are concerned. Not to mention the overly drawn out, drily delivered exposition at the start of every episode.\n\nThat said, at 13 episodes it`s still an easy recommendation. Watching two people work that hard at empathy is such a rare treat. Don`t miss this if you want some refreshingly straightforward romance.',
    },
    {
      type: 'Recommended',
      uid: 350281,
      content:
        'Space opera with an exciting buildup and a sublime crescendo. 4X players, don`t miss this!',
    },
    {
      type: 'Recommended',
      uid: 112858,
      content:
        'If you`re into scifi and generally more sophisticated stuff than brainless entertainment, this is a must see. Everyone else at least take a close look, you might be suprised.',
    },
    {
      type: 'Must See',
      uid: 411532,
      content: 'Strong characters and Great plot.  One of the best Space Opera`s I`ve seen.',
    },
    {
      type: 'Must See',
      uid: 284037,
      content: 'Awesome! Dunno what to say, but it`s just.... awesome!',
    },
    {
      type: 'Must See',
      uid: 125868,
      content:
        'This is the second best anime of all time, behind seikai no senki II closely followed by seikai no senki II.  This is a must see anime.  Excellenet plots, environment, characters, development, and re-watch value.',
    },
    {
      type: 'Must See',
      uid: 691547,
      content:
        'An awesome space opera\nthat tries to answer a simple yet complicated question:\nCan humans be friends with aliens?\nSo if you`re looking for an answer watch this.\nBtw think of this series as a small grandchild\nof a great EPIC like LoGH\nbut with Lafiel in the lead',
    },
  ],
  url: 'http://www.sunrise-inc.co.jp/seikai/',
  creators: [
    { id: 4303, type: 'Music', name: 'Hattori Katsuhisa' },
    { id: 4234, type: 'Direction', name: 'Nagaoka Yasuchika' },
    { id: 4516, type: 'Character Design', name: 'Watabe Keisuke' },
    { id: 8924, type: 'Series Composition', name: 'Yoshinaga Aya' },
    { id: 4495, type: 'Original Work', name: 'Morioka Hiroyuki' },
  ],
  resources: [
    { type: 1, externalEntity: [{ ids: ['14'], url: undefined }] },
    { type: 2, externalEntity: [{ ids: ['290'], url: undefined }] },
    { type: 3, externalEntity: [{ ids: ['376', 'xzudnt'], url: undefined }] },
    { type: 4, externalEntity: [{ ids: undefined, url: 'http://www.sunrise-inc.co.jp/seikai/' }] },
    { type: 6, externalEntity: [{ ids: ['Crest_of_the_Stars'], url: undefined }] },
    { type: 7, externalEntity: [{ ids: ['星界の紋章'], url: undefined }] },
    { type: 8, externalEntity: [{ ids: ['1333'], url: undefined }] },
    { type: 9, externalEntity: [{ ids: ['90291'], url: undefined }] },
    { type: 10, externalEntity: [{ ids: ['1869'], url: undefined }] },
    { type: 14, externalEntity: [{ ids: ['11753', 'v'], url: undefined }] },
    { type: 17, externalEntity: [{ ids: ['seikai01'], url: undefined }] },
    { type: 31, externalEntity: [{ ids: ['6674'], url: undefined }] },
  ],
  tags: [
    {
      id: 36,
      parentId: 2607,
      weight: 300,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'military',
      description:
        'The military, also known as the armed forces, are forces authorized and legally entitled to use deadly force so as to support the interests of the state and its citizens. The task of the military is usually defined as defence of the state and its citizens and the prosecution of war against foreign powers. The military may also have additional functions within a society, including construction, emergency services, social ceremonies, and guarding critical areas.\nSource: Wikipedia',
      pictureUrl: '212184.jpg',
      updatedAt: '2018-01-21',
    },
    {
      id: 1396,
      parentId: 2607,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'immortality',
      description:
        'Immortality is the ability to live in a physical or spiritual form for an infinite or inconceivably vast length of time. Humans, whose life span is limited and who die of age, disease and external trauma, have long sought ways to extend their lives; the Epic of Gilgamesh, considered one of the first great literary works created by mankind, is primarily the quest of a hero seeking to become immortal. The advances of science, in particular medicine and engineering, and especially in the last few centuries, have helped people extend their life span and may yet continue finding ways to do so.\nIn fiction, immortals are not quite as uncommon as in real life, and the possible implications of endless or very long lives are often explored. Such implications include, but are not limited to: repeatedly accompanying the deaths of those dear to them; having to hide their condition from the mortals surrounding them; becoming disillusioned with their lives and being unable to kill themselves; and even staying forever trapped in the body of a specific physical age, that body most often being that of a child. As such, while many may wish for immortality, it may be little more than a curse for the few who have it.',
      pictureUrl: undefined,
      updatedAt: '2014-10-01',
    },
    {
      id: 2008,
      parentId: 2891,
      weight: 200,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'small breasts',
      description:
        'This character has a bust size that is considered small. \nThe small size is usually a bust that would use a bra which is A or B. In anime, C may rarely enter this category.',
      pictureUrl: '162720.jpg',
      updatedAt: '2015-08-05',
    },
    {
      id: 2604,
      parentId: undefined,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'content indicators',
      description:
        'The content indicators branch is intended to be a less geographically specific tool than the `age rating` used by convention, for warning about things that might cause offence. Obviously there is still a degree of subjectivity involved, but hopefully it will prove useful for parents with delicate children, or children with delicate parents.\nRefer to further guidance on http://wiki.anidb.net/w/Categories:Content_Indicators [the Wiki page] for how to apply tag weights for content indicators.',
      pictureUrl: undefined,
      updatedAt: '2018-07-08',
    },
    {
      id: 2605,
      parentId: undefined,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'dynamic',
      description:
        'Some of the central structural elements in anime are: \nPlot Continuity \nHow does the plot or several plots unfold. Are they a strictly linear retelling of one big continuing story, a serial, possibly with several side stories, or is the content chopped into a set of unconnected episodes, only sharing the same setting and characters?\nStereotype Characters\nThen there is the question of the character set presentation. Is it completely original, or is it your usual stereotypical character cast. Both choices have their merit, for example it would not really make much sense to reinvent the wheel for a harem anime. Fans of that genre come to expect their favourite stereotype protagonists.\nPlot Twists\nFinally there is the question of how complex the plot / the story unfolds. Are there side-plots that merge into the main plot leading to unexpected plot twists, or is the anime quite predictable? The latter would not be appropriate for detective stories. In harem anime on the other hand a foreseeable outcome is actually something the fans will come to expect.',
      pictureUrl: undefined,
      updatedAt: '2014-09-28',
    },
    {
      id: 2607,
      parentId: undefined,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'themes',
      description:
        'Themes describe the very central elements important to the anime stories. They set the backdrop against which the protagonists must face their challenges. Be it School Life, present Daily Life, Military action, Cyberpunk, Law and Order detective work, Sports, or the Underworld. These are only but a few of the more typical backgrounds for anime plots. Add to that a Conspiracy setting with a possible tragic outcome, the Themes span most of the imaginable subject matter relevant to anime.',
      pictureUrl: undefined,
      updatedAt: '2009-04-29',
    },
    {
      id: 2608,
      parentId: undefined,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'fetishes',
      description:
        'Everything under fetishes (except for Bishounen and Juujin) is strictly only meant for hentai (18 Restricted) and ecchi anime. In case of ecchi, it must be the main element of the show and not when there`s only some of it, for example, there`s some ecchi in Shinseiki Evangelion, but the fact you get to see Asuka`s pantsu doesn`t warrant it the schoolgirl fetish category. So be careful to which ecchi show you add fetishes; it`s fairly straightforward with hentai, though. Overall, this category tree is to satisfy the needs of people with different fetishes, so they can search for what tingles their tangle; hence why this is restricted to hentai and full ecchi shows.',
      pictureUrl: undefined,
      updatedAt: '2012-12-04',
    },
    {
      id: 2609,
      parentId: undefined,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'original work',
      description:
        'What the anime is based on! This is given as the original work credit in the OP. Mostly of academic interest, but a useful bit of info, hinting at the possible depth of story.',
      pictureUrl: undefined,
      updatedAt: '2018-09-01',
    },
    {
      id: 2610,
      parentId: undefined,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'setting',
      description:
        'The setting describes in what time and place an anime takes place. To a certain extent it describes what you can expect from the world in the anime.',
      pictureUrl: undefined,
      updatedAt: '2009-04-22',
    },
    {
      id: 2611,
      parentId: undefined,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'elements',
      description:
        'Next to Themes setting the backdrop for the protagonists in anime, there are the more detailed plot Elements that centre on character interactions: "What do characters do to each other or what is done to them?". Is it violent Action, an awe-inspiring Adventure in a foreign place, the gripping life of a Detective, a slapstick Comedy, an Ecchi Harem anime, a SciFi epic, or some Fantasy travelling adventure?',
      pictureUrl: undefined,
      updatedAt: '2014-09-08',
    },
    {
      id: 2612,
      parentId: 2610,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'time',
      description:
        'This placeholder lists different epochs in human history and more vague but important timelines such as the future, the present and the past.',
      pictureUrl: undefined,
      updatedAt: '2016-09-04',
    },
    {
      id: 2613,
      parentId: 2610,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'place',
      description:
        'The places the anime can take place in. Includes more specific places such as a country on Earth, as well as more general places such as a dystopia or a mirror world.',
      pictureUrl: undefined,
      updatedAt: '2016-09-04',
    },
    {
      id: 2619,
      parentId: 2841,
      weight: 200,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'gunfights',
      description: 'Fights where two or more parties are firing guns at one another.',
      pictureUrl: '211280.jpg',
      updatedAt: '2017-12-26',
    },
    {
      id: 2626,
      parentId: 2612,
      weight: 600,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'future',
      description:
        'Anime that fall under the future category are the ones that have a society that could have originated from ours. In most cases it should go hand to hand with sci-fi since we expect the future to consist of advanced technology, however, in the case where it`s explicitly stated in the story that the anime takes place "x years into the future", the state of technology doesn`t matter as long as it`s long into the future. The anime can be set in an alternative universe not tied with our own, as long as it has a futuristic feel to it.\nThis category sports quite a lot of anime, mostly stemming from SciFi, but not necessarily only from there.',
      pictureUrl: undefined,
      updatedAt: '2009-05-15',
    },
    {
      id: 2627,
      parentId: 2613,
      weight: 600,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'space',
      description: 'The final frontier.',
      pictureUrl: undefined,
      updatedAt: '2009-04-20',
    },
    {
      id: 2636,
      parentId: 2846,
      weight: 200,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'human enhancement',
      description:
        'The enhancement of humans can take various forms: It can be something comparatively non-intrusive as a power-up drug, a form of machine implantation or cyberization ("SAC Solid State Society"), or outright - possibly atrocious - genetic manipulation ("Ao no 6-gou"). Plot-wise enhanced protagonists in anime usually have to pay a price for their enhancements, be it physical or mental.',
      pictureUrl: undefined,
      updatedAt: '2015-10-06',
    },
    {
      id: 2639,
      parentId: 2846,
      weight: 500,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'space travel',
      description:
        'Space Travel usually refers going to space or travelling there with or without a spacecraft. There are different forms of space travel like Interplanetary travel, Interstellar travel or Intergalactic travel. Since it isn`t possible to travel faster than light, most anime series involve some sort "sub-space travel mechanism" as a way to travel faster than light.',
      pictureUrl: undefined,
      updatedAt: '2009-04-29',
    },
    {
      id: 2660,
      parentId: 2627,
      weight: 400,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'other planet',
      description:
        'The anime will fit this category if some or all of the action takes place on another planet which is supposedly in the same universe as Earth, not a complete fantasy world; usually there has to be some concept of space travel. The Latin name for Earth - Terra, would also pass the condition of being in the same universe as Earth. Basically, even mentioning of Earth existing or having existed would be enough. Although Moon is a moon, it also qualifies as Other Planet.',
      pictureUrl: undefined,
      updatedAt: '2009-05-15',
    },
    {
      id: 2661,
      parentId: 2627,
      weight: 400,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'shipboard',
      description:
        'Beam me up, Scotty! Space stations (think Death Star) also count. Basically, this category is to tell if the setting takes place onboard a spaceship in space. This category is not applicable if the spaceship lies on a planet and never actually gets into space.',
      pictureUrl: undefined,
      updatedAt: '2009-05-18',
    },
    {
      id: 2741,
      parentId: 2891,
      weight: 200,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'large breasts',
      description:
        'Large breasts are breasts a fair notch larger than average, as found in some adolescent girls or fully grown women; however, as anime has no upper limit to breast size, the definition applies somewhat differently. To be considered large, breasts in anime must be bigger than real-life natural ones or natural-seeming fake ones, to the point they`d appear weirdly or even abnormally large in real-life females. On the high end of the spectrum, breasts that are as big as the character`s head or possibly a bit bigger are still considered large; however, breasts that take at least as much space as the rest of the chest or the abdomen, or that are almost as big but have an absurdly unnatural shape, are the less common http://anidb.net/t1774 [gigantic breasts] instead.',
      pictureUrl: '161014.jpg',
      updatedAt: '2015-12-14',
    },
    {
      id: 2749,
      parentId: 2604,
      weight: 100,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'nudity',
      description:
        'Nudity is the state of wearing no clothing. The wearing of clothing is exclusively a human characteristic. The amount of clothing worn depends on functional considerations (such as a need for warmth or protection from the elements) and social considerations. In some situations the minimum amount of clothing (i.e. covering of a person`s genitals) may be socially acceptable, while in others much more clothing is expected.\nRefer to further guidance on http://wiki.anidb.net/w/Categories:Content_Indicators [the Wiki page] for how to apply tag weights for content indicators.\nPeople, as individuals and in groups, have varying attitudes towards their own nudity. Some people are relaxed about appearing less than fully clothed in front of others, while others are uncomfortable or inhibited in that regard. People are nude in a variety of situations, and whether they are prepared to disrobe in front of others depends on the social context in which the issue arises. For example, people need to bathe without clothing, some people also sleep in the nude, some prefer to sunbathe in the nude or at least topless, while others are nude in other situations. Some people adopt naturism as a lifestyle.\nThough the wearing of clothes is the social norm in most cultures, some cultures, groups and individuals are more relaxed about nudity, though attitudes often depend on context. On the other hand, some people feel uncomfortable in the presence of any nudity, and the presence of a nude person in a public place can give rise to controversy, irrespective of the attitude of the person who is nude. Besides meeting social disapproval, in some places public nudity may constitute a crime of indecent exposure. Many people have strong views on nudity, which to them can involve issues and standards of modesty, decency and morality. Some people have an psychological aversion to nudity, called gymnophobia. Many people regard nudity to be inherently sexual and erotic.\nNudity is to be found in a multitude of media, including art, photography, film and on the Internet. It is a factor in adult entertainment of various types.\nEspecially gratuitous fanservice anime shows tend to show their (usually female) characters frequently without any clothes, though often hiding genitals through the means of additions like steam.\nSource: wiki',
      pictureUrl: '60576.jpg',
      updatedAt: '2018-07-08',
    },
    {
      id: 2778,
      parentId: 2858,
      weight: 300,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'slow when it comes to love',
      description:
        'The main protagonists in this anime have a very hard time trying to express their feelings to each other. They simply will not finally confess their love.\nIn some cases this romance element is based on unrequited love, or an absurd amount of shyness.',
      pictureUrl: undefined,
      updatedAt: '2012-11-09',
    },
    {
      id: 2790,
      parentId: 2605,
      weight: 600,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'plot continuity',
      description:
        'Consistency of the characteristics of persons, plot, objects, places and events seen by the viewer.\nA single linear focused plot is highly continuous.\nA truly random plot is highly discontinuous.',
      pictureUrl: undefined,
      updatedAt: '2010-01-17',
    },
    {
      id: 2799,
      parentId: 2609,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'novel',
      description:
        'Note that novel means book with words in paper, so no comics and no "visual novels", which should go under manga and dating-sim - visual Novel/erotic game respectively.\nNote that it can be applied to novels as we know them but also the typical light novels for teens and young adults, which are common in Japan and aside from being short include a number of illustrations.',
      pictureUrl: undefined,
      updatedAt: '2010-05-14',
    },
    {
      id: 2841,
      parentId: 2611,
      weight: 400,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'action',
      description:
        'Action anime usually involve a fairly straightforward story of good guys versus bad guys, where most disputes are resolved by using physical force. It often contains a lot of shooting, explosions and fighting.',
      pictureUrl: '211261.jpg',
      updatedAt: '2017-12-26',
    },
    {
      id: 2846,
      parentId: 7050,
      weight: 500,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'science fiction',
      description:
        'Science fiction stories usually focus on how situations could be different in the future when we are more technologically advanced; due to either our own achievements or having met with other civilizations whom we have learned from.',
      pictureUrl: '212180.jpg',
      updatedAt: '2018-01-21',
    },
    {
      id: 2849,
      parentId: 7050,
      weight: 100,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'fantasy',
      description:
        'Fantasy is a genre of fiction that uses magic and other supernatural phenomena as a primary element of plot, theme, or setting. Many works within the genre take place in fictional worlds where magic is common. Fantasy is generally distinguished from science fiction and horror by the expectation that it steers clear of (pseudo-)scientific and macabre themes, respectively, though there is a great deal of overlap between the three (which are subgenres of speculative fiction).\nIn popular culture, the genre of fantasy is dominated by its medievalist form, especially since the worldwide success of The Lord of the Rings books by J. R. R. Tolkien. In its broadest sense however, fantasy comprises works by many writers, artists, filmmakers, and musicians, from ancient myths and legends to many recent works embraced by a wide audience today.\nFantasy is a vibrant area of academic study in a number of disciplines (English, cultural studies, comparative literature, history, medieval studies). Work in this area ranges widely, from the structuralist theory of Tzvetan Todorov, which emphasizes the fantastic as a liminal space, to work on the connections (political, historical, literary) between medievalism and popular culture\nSource: Wiki',
      pictureUrl: '68768.jpg',
      updatedAt: '2005-05-07',
    },
    {
      id: 2850,
      parentId: 2611,
      weight: 500,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'adventure',
      description:
        'Adventures are exciting stories, with new experiences or exotic locales. Adventures are designed to provide an action-filled, energetic experience for the viewer. Rather than the predominant emphasis on violence and fighting that is found in pure action anime, however, the viewer of adventures can live vicariously through the travels, conquests, explorations, creation of empires, struggles and situations that confront the main characters, actual historical figures or protagonists. Under the category of adventures, we can include traditional swashbucklers, serialized films, and historical spectacles, searches or expeditions for lost continents, "jungle" and "desert" epics, treasure hunts and quests, disaster films, and heroic journeys or searches for the unknown. Adventure films are often, but not always, set in an historical period, and may include adapted stories of historical or literary adventure heroes, kings, battles, rebellion, or piracy.',
      pictureUrl: '178879.jpg',
      updatedAt: '2015-10-25',
    },
    {
      id: 2858,
      parentId: 2611,
      weight: 300,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'romance',
      description:
        'Romance describes a story that deals with love between two or more characters typically also having an optimistic ending. Romance is also a difficulty encountered when creating a harem.',
      pictureUrl: '210061.jpg',
      updatedAt: '2017-12-01',
    },
    {
      id: 2868,
      parentId: 2607,
      weight: 200,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'racism',
      description:
        'Racism is prejudice, discrimination, or antagonism directed against someone of an ethnically different background based on the pseudo-scientific belief that biological differences between peoples form so-called "races" and that one`s own "race" is superior to another, possibly also holding that members of different "races" should be treated differently. Some definitions include only consciously malignant forms of discrimination, and some views include discriminatory behaviors and beliefs based on cultural, national, ethnic, caste, or religious stereotypes. In works of fiction, this may also include similar actions against other sentient species.\nSource: Wikipedia',
      pictureUrl: undefined,
      updatedAt: '2015-12-20',
    },
    {
      id: 2874,
      parentId: 2607,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'disaster',
      description:
        'A disaster is a large-scale situation that causes great loss of or damage or threat to life, health, property, society, or the environment, irrespective of its source or cause. Disasters have substantial, long-lasting negative repercussions, and great effort must be spent in order to undo or mitigate their effects.',
      pictureUrl: undefined,
      updatedAt: '2018-05-07',
    },
    {
      id: 2891,
      parentId: 2608,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'breasts',
      description:
        'The female bust size matters! Or does it? The three subcategories spell out the sizes that relate to fetishes, be they gigantic, large or small. Normal sized breasts are not a fetish, it seems. The tag is not only used for ecchi anime, but also for hentai shows as well.',
      pictureUrl: '161015.jpg',
      updatedAt: '2014-12-31',
    },
    {
      id: 2907,
      parentId: 2636,
      weight: 400,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'genetic modification',
      description:
        'Story-wise, genetic modification is usually centred on humans, probably the most subtle and creepy way of messing with mankind. Playing with the fear of the unknown, genetically altered humans are technically a new species, that may not only surpass but actually replace unaltered humans. The level of modification will vary from subtle changes in "look" (e.g. super-human beauty), to mental enhancements (PSI powers), to more or less atrocious adaptations to extreme environments (breath under water, radiation resistance). Note that changes in Aliens would be difficult to pinpoint, after all they are alien.',
      pictureUrl: undefined,
      updatedAt: '2015-09-24',
    },
    {
      id: 2925,
      parentId: 2874,
      weight: 400,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'war',
      description:
        'War is a phenomenon of organized violent conflict, typified by extreme aggression, societal disruption and adaptation, and high mortality. The objective of warfare differs in accord with a group`s role in a conflict: The goals of offensive warfare are typically the submission, assimilation or destruction of another group, while the goals of defensive warfare are simply the repulsion of the offensive force and, often, survival itself. Relative to each other, combatants in warfare are called enemies. The terms military, militant, and militarism each refer to fundamental aspects of war, i.e. the organized group, the combative individual, and the supportive ethos (respectively).\nSource: wiki',
      pictureUrl: '56441.jpg',
      updatedAt: '2012-10-07',
    },
    {
      id: 3138,
      parentId: 6151,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'fictional language',
      description:
        'Fictional languages are intended to be the languages of a fictional world and are often designed with the intent of giving more depth and an appearance of plausibility to the fictional worlds with which they are associated, and to have their characters communicate in a fashion which is both alien and dislocated.\nSome of these languages, e.g. in worlds of fantasy fiction, alternative universes, Earth`s future, or alternate history, are presented as distorted versions or dialects of modern English or other natural language, while others are independently designed conlangs.\nA fictional language often has the least amount of grammar and vocabulary possible, and rarely extends beyond the absolutely necessary. At the same time, some others have developed languages in detail for their own sake, such as J. R. R. Tolkien`s Quenya and Sindarin and Star Trek`s Klingon language which exist as functioning, usable languages. Here "fictional" can be a misnomer.',
      pictureUrl: undefined,
      updatedAt: '2014-10-08',
    },
    {
      id: 3489,
      parentId: 2841,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'car chases',
      description: 'Car chases occur as part of the action setting in this anime.',
      pictureUrl: '211263.jpg',
      updatedAt: '2017-12-26',
    },
    {
      id: 3589,
      parentId: 6230,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'multiple protagonists',
      description: undefined,
      pictureUrl: undefined,
      updatedAt: '2011-03-06',
    },
    {
      id: 3683,
      parentId: 2605,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'storytelling',
      description: undefined,
      pictureUrl: undefined,
      updatedAt: '2014-09-28',
    },
    {
      id: 3929,
      parentId: 2607,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'sociocultural evolution',
      description:
        'Describes how cultures and societies develop over time, based on both cultural evolution and social evolution.\nA post-apocalyptic or a Utopian setting would show very interesting changes in human behaviour, mental state, or simply daily life.',
      pictureUrl: '191062.jpg',
      updatedAt: '2016-09-09',
    },
    {
      id: 3977,
      parentId: 3683,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'dialogue driven',
      description:
        'A dialogue driven show has its story advanced by dialogue, with action being of much lower priority, and relies heavily on conversations between characters.',
      pictureUrl: undefined,
      updatedAt: '2008-12-29',
    },
    {
      id: 4022,
      parentId: 6230,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'strong female lead',
      description:
        'The lead female character has a strong personality and plays a part that is not the typical damsel-in-distress role. \nThis is the exact opposite of the “damsel in distress” tag.',
      pictureUrl: undefined,
      updatedAt: '2010-11-29',
    },
    {
      id: 4081,
      parentId: 2841,
      weight: 400,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'space battles',
      description:
        'There are space battles in this anime. Usually between Earth forces and some alien invader, but ship to ship skirmishes in deep space are just as common.',
      pictureUrl: undefined,
      updatedAt: '2008-06-02',
    },
    {
      id: 4440,
      parentId: 2858,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'boy meets girl',
      description:
        'A classical type of plot in story writing, where the story begins with a boy meeting a girl leading to romantic development between the two. More often than not the boy loses the girl later on and has to find her again.',
      pictureUrl: undefined,
      updatedAt: '2010-02-01',
    },
    {
      id: 4446,
      parentId: 2639,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'faster-than-light travel',
      description:
        'Faster-than-light travel is taken for grated in this anime. This is achieved by travelling via hyperspace, nullspace, or wormholes.',
      pictureUrl: undefined,
      updatedAt: '2017-12-12',
    },
    {
      id: 4480,
      parentId: 6246,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: true,
      name: 'happy ending',
      description:
        'And they lived "happily ever after"... *sniff*.\nAll issues in the anime have been resolved, the love polygons sorted out, the conflicts resolved, the guy gets the girl (or the other way around), and everyone else lives on blissfully.\n(Not very realistic, but then again this is anime.)',
      pictureUrl: '222185.jpg',
      updatedAt: '2018-08-13',
    },
    {
      id: 4537,
      parentId: 2605,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'time skip',
      description:
        'The plot features at least one skip or jump in time.\nExample: A skip from the present into the past, or time skips in increments, e.g. every hour there is a time skip by a day.',
      pictureUrl: undefined,
      updatedAt: '2014-02-15',
    },
    {
      id: 4665,
      parentId: 2607,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'propaganda',
      description:
        'Propaganda is communication aimed at influencing the attitude of a community toward some cause or position. As opposed to impartially providing information, propaganda in its most basic sense, presents information primarily to influence an audience. Propaganda often presents facts selectively (thus lying by omission) to encourage a particular synthesis, or uses loaded messages to produce an emotional rather than rational response to the information presented. The desired result is a change of the attitude toward the subject in the target audience to further a political agenda.',
      pictureUrl: undefined,
      updatedAt: '2015-02-26',
    },
    {
      id: 5003,
      parentId: 2607,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'imperialism',
      description:
        'Imperialism is a type of advocacy of empire. Its name originated from the Latin word "imperium", which means to rule over large territories. Imperialism is "a policy of extending a country`s power and influence through colonization, use of military force, or other means".\nSource: Wiki',
      pictureUrl: undefined,
      updatedAt: '2015-12-10',
    },
    {
      id: 5929,
      parentId: 2846,
      weight: 400,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'space opera',
      description:
        'Space opera is a sub-genre of fiction that emphasizes romantic adventures in space. Space opera generally involves large-scale conflicts between opponents with powerful abilities and technology. The genre will often be melodramatic, sometimes playing music that can be nothing short of awesome. Warfare and a battle of wits are usually less emphasized, preferring romance (with exceptions, e.g. Ginga Eiyuu Densetsu). Some space operas tend to be formulaic and sometimes even prosaic, often employing very simple devices and somewhat obvious strategies. An example of this would be the infamous laws of physics in the Macross universe, in which the main male lead will hardly ever get hit in battle.',
      pictureUrl: undefined,
      updatedAt: '2014-09-10',
    },
    {
      id: 6151,
      parentId: undefined,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'technical aspects',
      description:
        'It may sometimes be useful to know about technical aspects of a show, such as information about its broadcasting or censorship. Such information can be found here.',
      pictureUrl: undefined,
      updatedAt: '2014-09-10',
    },
    {
      id: 6230,
      parentId: 2605,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'cast',
      description: undefined,
      pictureUrl: undefined,
      updatedAt: '2014-10-20',
    },
    {
      id: 6246,
      parentId: 2605,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'ending',
      description:
        'This is a container tag to house meta-like tags relating to how endings of anime play out.',
      pictureUrl: undefined,
      updatedAt: '2018-08-06',
    },
    {
      id: 7050,
      parentId: 2611,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'speculative fiction',
      description: undefined,
      pictureUrl: undefined,
      updatedAt: '2018-01-02',
    },
  ],
  characters: [
    {
      id: 28,
      type: 'main character in',
      updatedAt: '2012-07-25',
      rating: 9.2,
      votes: 1182,
      name: 'Abriel Nei Debrusc Borl Paryun Lafiel',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description:
        'Ablïarsec néïc Dubreuscr Bœrh Parhynr Lamhirh (a.k.a., Viscountess Paryunu Abriel Nei Dobrusk Lafiel) is the main female protagonist in the anime Crest of the Stars, Banner of the Stars, and Banner of the Stars II, as well as all the novels written by Morioka Hiroyuki on which the shows were based. She is a strong-willed Abh princess (granddaughter of the Abh empress) who has a steely exterior, but ends up befriending Ghintec Linn (Jinto Lynn in the Martinh tongue). Like all Abh, she has bluish hued hair, and has a natural lifespan of over 200 years. Lamhirh also has lapis lazuli colored eyes. As an Ablïarsec, she has pointed ears, yet hers are markedly less so than other Ablïarsec. This is because half her genes (those not from her father) are from someone outside the Abriel clan and her father chose not to make any unnecessary alterations in her genes. She is deemed "child of love" (an Abh child with the genes of the parent, and the one the parent loves). Her full name can be roughly translated to Lamhirh (néïc Dubleuscr) Ablïarsec, Viscountess of Parhyn.\nDespite being a princess, she rarely acts like one and hates being treated as one. One of the reasons she took a liking towards Ghintec is because when they first met, he neither recognized her as a princess nor treated her as one. Their relationship is so close that she freely allows him to use her real name of Lamhirh when addressing her, something that is very uncommon when addressing those of nobility or royalty.\nShe acts remarkably older than her age (at her introduction in Crest of the Stars, she is 16 years old) and can, in most cases, logically think her way out of most situations. However, her headstrong nature sometimes clouds her judgement and can lead her to become impulsive. An example of this is when she is reprimanded by Laicch for wishing to stay behind on the Gothlauth instead of continuing her mission of escorting Ghintec to the capital. She believes that she would have been of more use fighting with the crew rather than abandoning them. She is quickly shown how wrong her line of reasoning is and how much more disgraceful it would have been to abandon Ghintec and her mission. She is a remarkably good shot and although she sometimes doubts herself, she proves to be a worthy ship captain (deca-commander) in Banner of the Stars. She shows little emotion throughout Crest of the Stars, but as time goes by became very close friend with Ghintec through Banner of the Stars. This is especially true in later installments, where she more frequently questions how their friendship will last due to the doubt of Ghintec`s lifespan.\nShe is one of the candidates for the Abh Imperial Throne and, as indicated by her full name, she is the Viscountess of Parhynh, the so-called "Country, or Nation, of Roses."',
      picture: '14304.jpg',
      seiyuu: [{ id: 12, picture: '184301.jpg', name: 'Kawasumi Ayako' }],
    },
    {
      id: 4079,
      type: 'secondary cast in',
      updatedAt: '2009-02-28',
      rating: 6.17,
      votes: 19,
      name: 'Abriel Nei Debrusc Larth Kryb Debeus',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description: 'Lafiel`s father, the King of Kryv and a son of the current reigning empress.',
      picture: '20037.jpg',
      seiyuu: [{ id: 3136, picture: '24121.jpg', name: 'Suzuoki Hirotaka' }],
    },
    {
      id: 4080,
      type: 'secondary cast in',
      updatedAt: '2009-02-28',
      rating: 8.79,
      votes: 30,
      name: 'Lexshu Wef-Robell Plakia',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description:
        'The captain of the Gosroth (Gothlauth), she is every bit as smart, beautiful, dedicated and stubborn as Lafiel, but older and wiser. Judging from her name, Lexshu`s rank in the Abh social hierarchy is that of a reucec (knight or dame).',
      picture: '20038.jpg',
      seiyuu: [{ id: 404, picture: '151682.jpg', name: 'Takashima Gara' }],
    },
    {
      id: 4081,
      type: 'main character in',
      updatedAt: '2012-07-25',
      rating: 7.52,
      votes: 210,
      name: 'Linn Syun-Rock Dreu Haider Jinto',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description:
        'Born Jinto Lynn on planet Martine (spelt as Martinh in Baronh) of the Hyde star system (Haïdec in Baronh), he was the son of Rock Lynn, a politician who eventually became president of the Hyde star system. It was during his administration that the Abh empire was able to annex the Hyde stellar system into its territory through an invasion. Making his own ideas more valuable than the rights of the people of Martine, Rock Lin made a deal with the leaders of the invading forces that the territorial lord of Hyde shall be chosen amongst the people of Martine. The leader of the invading forces agreed to this however this meant that an election cannot be held making Rock, as the current leader of Martine, the natural choice to become its territorial lord. Because of this, Rock Lynn, and with him, Jinto, rose to the ranks of Abh nobility as Count of Haïdec.',
      picture: '20036.jpg',
      seiyuu: [{ id: 362, picture: '74735.jpg', name: 'Imai Yuka' }],
    },
    {
      id: 4082,
      type: 'secondary cast in',
      updatedAt: '2009-02-28',
      rating: 8.71,
      votes: 63,
      name: 'Abriel Nei Lamsar Larth Balkei Dusanyu',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description:
        'The current Dusanyu, or Crown Prince, of the Abh Empire of Mankind, the Baronh name of which is Frybar Gloer Gor Bari (Frybarec Gloer Gor Bari), Also the Commander-in-Chief of the Abh Armed Forces, who personally led the invasion of the Hyde star system.',
      picture: '20035.jpg',
      seiyuu: [{ id: 1819, picture: '20694.jpg', name: 'Shiozawa Kaneto' }],
    },
    {
      id: 4083,
      type: 'secondary cast in',
      updatedAt: '2009-02-28',
      rating: 6.69,
      votes: 19,
      name: 'Trife Boli Yuvdale Remsale',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description:
        'Despite verging on excessive caution, he is nonetheless one of the most able tacticians in the Labule. He puts every aspect and factor under consideration, frequently asking his subordinates` opinions and assessments before starting an operation. He is also one of the least loved officers.',
      picture: '20034.jpg',
      seiyuu: [{ id: 220, picture: '17038.jpg', name: 'Kosugi Juurouta' }],
    },
    {
      id: 4084,
      type: 'secondary cast in',
      updatedAt: '2009-02-28',
      rating: 9.08,
      votes: 224,
      name: 'Spoor Aron Sekpadao Letopanyu Peneju',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description:
        'This red-eyed Grand Duchess is one of the most eccentric officers in the Labule, which does not change the fact that she is one of its most able admirals. Though complaining of boredom most of the time, she suddenly springs into action when needed. One of her favourite pastimes is mercilessly teasing Kaselia, her chief of staff.',
      picture: '20033.jpg',
      seiyuu: [{ id: 1509, picture: '19311.jpg', name: 'Fukami Rika' }],
    },
    {
      id: 4085,
      type: 'secondary cast in',
      updatedAt: '2009-02-28',
      rating: 2.84,
      votes: 16,
      name: 'Atosryua Syun-Atos Lyuf Raika Febdak Klowal',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description:
        'The third Baron of Febdak (Faibdash), an obscure star system where Jinto and Lafiel made a stopover en route to Safugnoff (Sfagnaumh). He had an inferiority complex due to his clan`s origins and brief history, causing him to confine and isolate his own father. He tried to abduct Lafiel and imprison Jinto, which brought dire consequences onto himself.',
      picture: '20032.jpg',
      seiyuu: [{ id: 139, picture: '29283.jpg', name: 'Koyasu Takehito' }],
    },
    {
      id: 4086,
      type: 'secondary cast in',
      updatedAt: '2009-02-28',
      rating: 6.64,
      votes: 16,
      name: 'Atosryua Syun-Atos Lyuf Raika Febdak Srguf',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description:
        'The second Baron of Febdak and father of Klowal. Srguf`s mother was the first Baroness, who gained distinction by rising through the Imperial Star Force, or Labule (Laburec). Due to his being a genetic "grounder," his own son despised him resulting in confinement and isolation. He eventually befriended Jinto and aided Lafiel in "punishing" Klowal. His daughter, Loïc eventually became the Baroness of Febdak and a commanding officer to Lafiel and Jinto.',
      picture: '20039.jpg',
      seiyuu: [{ id: 39, picture: '16629.jpg', name: 'Mugihito' }],
    },
    {
      id: 4087,
      type: 'appears in',
      updatedAt: '2009-02-28',
      rating: 5.33,
      votes: 5,
      name: 'Entoryua Rei',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '20044.jpg',
      seiyuu: [{ id: 339, picture: '79312.jpg', name: 'Ishizuka Unshou' }],
    },
    {
      id: 4088,
      type: 'secondary cast in',
      updatedAt: '2009-02-28',
      rating: 1.41,
      votes: 6,
      name: 'Kaito',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '20045.jpg',
      seiyuu: [{ id: 3312, picture: '24691.jpg', name: 'Ikemizu Michihiro' }],
    },
    {
      id: 7493,
      type: 'appears in',
      updatedAt: '2010-12-03',
      rating: 6.14,
      votes: 2,
      name: 'Gosroth',
      gender: 'unknown',
      characterType: { id: 4, name: 'Vessel' },
      description: 'The Resii Gothroth.\nThe first Abh ship lost in the war.',
      picture: '60215.jpg',
      seiyuu: [],
    },
    {
      id: 7501,
      type: 'appears in',
      updatedAt: '2014-02-15',
      rating: 3.81,
      votes: 1,
      name: 'Wakusei Martine',
      gender: 'unknown',
      characterType: { id: 3, name: 'Organization' },
      description: 'The homeworld of Jinto',
      picture: '150280.jpg',
      seiyuu: [],
    },
    {
      id: 7503,
      type: 'appears in',
      updatedAt: '2009-05-27',
      rating: 3.35,
      votes: 2,
      name: 'Rock Lynn',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description:
        'The former president of Martine, later made count of the Hyde system, after striking a deal with the Abh (in episode 1)',
      picture: '26165.jpg',
      seiyuu: [{ id: 1733, picture: '25839.jpg', name: 'Tanaka Hideyuki' }],
    },
    {
      id: 7512,
      type: 'secondary cast in',
      updatedAt: '2009-05-27',
      rating: 2.98,
      votes: 5,
      name: 'Jinto Lynn',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description: 'Jinto, before he became a noble of the Abh.',
      picture: '26167.jpg',
      seiyuu: [],
    },
    {
      id: 7514,
      type: 'appears in',
      updatedAt: '2009-05-27',
      rating: 8.15,
      votes: 12,
      name: 'Abh Teikoku',
      gender: 'unknown',
      characterType: { id: 3, name: 'Organization' },
      description: undefined,
      picture: '26171.jpg',
      seiyuu: [],
    },
    {
      id: 7516,
      type: 'appears in',
      updatedAt: '2009-05-27',
      rating: 1.92,
      votes: 3,
      name: 'Till Corinth',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '26175.jpg',
      seiyuu: [{ id: 4193, picture: '154158.jpg', name: 'Suzuki Eiichirou' }],
    },
    {
      id: 21911,
      type: 'appears in',
      updatedAt: '2010-09-27',
      rating: 5.54,
      votes: 5,
      name: 'Lina Clint',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '55529.jpg',
      seiyuu: [{ id: 4708, picture: '94172.jpg', name: 'Hosono Masayo' }],
    },
    {
      id: 21943,
      type: 'secondary cast in',
      updatedAt: '2010-09-28',
      rating: 5.97,
      votes: 8,
      name: 'Ku Dorin',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '55561.jpg',
      seiyuu: [{ id: 2799, picture: '23198.jpg', name: 'Matsuno Taiki' }],
    },
    {
      id: 21944,
      type: 'secondary cast in',
      updatedAt: '2010-09-28',
      rating: 4.8,
      votes: 3,
      name: 'Gyumuryua',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '55562.jpg',
      seiyuu: [{ id: 17008, picture: '46192.jpg', name: 'Fuji Takako' }],
    },
    {
      id: 21945,
      type: 'secondary cast in',
      updatedAt: '2010-09-28',
      rating: 7.15,
      votes: 2,
      name: 'Deesh',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '55563.jpg',
      seiyuu: [{ id: 1913, picture: '186187.jpg', name: 'Chiba Isshin' }],
    },
    {
      id: 21946,
      type: 'secondary cast in',
      updatedAt: '2010-09-28',
      rating: 5.14,
      votes: 2,
      name: 'Lairia',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '55564.jpg',
      seiyuu: [{ id: 370, picture: '204461.jpg', name: 'Yusa Kouji' }],
    },
    {
      id: 21947,
      type: 'secondary cast in',
      updatedAt: '2010-09-28',
      rating: 6.17,
      votes: 2,
      name: 'Leshikuna',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '55566.jpg',
      seiyuu: [{ id: 2899, picture: '79024.jpg', name: 'Miyazaki Issei' }],
    },
    {
      id: 21948,
      type: 'secondary cast in',
      updatedAt: '2010-09-28',
      rating: 4.2,
      votes: 2,
      name: 'Saryush',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '55567.jpg',
      seiyuu: [{ id: 399, picture: '17244.jpg', name: 'Suyama Akio' }],
    },
    {
      id: 21949,
      type: 'secondary cast in',
      updatedAt: '2010-09-28',
      rating: 4.8,
      votes: 3,
      name: 'Yunseryua',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '55568.jpg',
      seiyuu: [{ id: 21499, picture: '188514.jpg', name: 'Tomokawa Mari' }],
    },
    {
      id: 21954,
      type: 'secondary cast in',
      updatedAt: '2011-04-08',
      rating: 5.38,
      votes: 7,
      name: 'Abriel Nei Debrusc Spunej Ramaj',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description:
        'The 37th and current reigning empress of the Abh Empire, she is also Lafiel`s grandmother. She also holds the title "Dreuc Ablïarser" (Countess of Ablïarsec; Ablïarsec is also the name of the stellar system where Lakfakalle (Lacmhacarh), the imperial capital, is located).',
      picture: '55576.jpg',
      seiyuu: [{ id: 542, picture: '60897.jpg', name: 'Doi Mika' }],
    },
    {
      id: 21958,
      type: 'appears in',
      updatedAt: '2015-02-07',
      rating: 8.05,
      votes: 3,
      name: 'Futune',
      gender: 'none/does not apply',
      characterType: { id: 4, name: 'Vessel' },
      description: undefined,
      picture: '55580.jpg',
      seiyuu: [],
    },
    {
      id: 40209,
      type: 'appears in',
      updatedAt: '2012-01-04',
      rating: 5.34,
      votes: 15,
      name: 'Diaho',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description:
        'Jinto`s cat.\n\nLafiel gave him to Jinto at the end of http://anidb.net/a1 [Seikai no Monshou].\nHe is the son of Zanelia who is the daughter of Holia.',
      picture: '79471.jpg',
      seiyuu: [],
    },
    {
      id: 49519,
      type: 'appears in',
      updatedAt: '2012-09-30',
      rating: 2.5,
      votes: 2,
      name: 'Seelnay',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '50186.jpg',
      seiyuu: [{ id: 7, picture: '186500.jpg', name: 'Ootani Ikue' }],
    },
  ],
  episodes: [
    {
      id: 1,
      updatedAt: '2011-07-01',
      episodeNumber: '1',
      type: 1,
      length: 25,
      airDate: '1999-01-03',
      rating: 3.3,
      votes: 28,
      titles: [
        { title: '侵略', language: 'ja' },
        { title: 'Invasion', language: 'en' },
        { title: 'Invasion', language: 'fr' },
        { title: 'Shinryaku', language: 'x-jat' },
      ],
      summary: null
    },
    {
      id: 2,
      updatedAt: '2011-07-01',
      episodeNumber: '2',
      type: 1,
      length: 25,
      airDate: '1999-01-10',
      rating: 4.94,
      votes: 22,
      titles: [
        { title: '星たちの眷族', language: 'ja' },
        { title: 'Kin of the Stars', language: 'en' },
        { title: 'Les parents des Étoiles', language: 'fr' },
        { title: 'Hoshi-tachi no Kenzoku', language: 'x-jat' },
      ],
      summary: null
    },
    {
      id: 1009,
      updatedAt: '2011-07-01',
      episodeNumber: '10',
      type: 1,
      length: 25,
      airDate: '1999-03-07',
      rating: 6.86,
      votes: 17,
      titles: [
        { title: '二人だけの逃亡', language: 'ja' },
        { title: 'Escape: Just the Two of Us', language: 'en' },
        { title: 'Fuite à deux', language: 'fr' },
        { title: 'Futari dake no Toubou', language: 'x-jat' },
      ],
      summary: null
    },
    {
      id: 1010,
      updatedAt: '2011-07-01',
      episodeNumber: '5',
      type: 1,
      length: 25,
      airDate: '1999-01-31',
      rating: 8.06,
      votes: 20,
      titles: [
        { title: 'ゴースロスの戦い', language: 'ja' },
        { title: 'The Battle of Gosroth', language: 'en' },
        { title: 'La bataille du Gothlauth', language: 'fr' },
        { title: 'Gosroth no Tatakai', language: 'x-jat' },
      ],
      summary: null
    },
    {
      id: 1011,
      updatedAt: '2011-07-01',
      episodeNumber: '4',
      type: 1,
      length: 25,
      airDate: '1999-01-24',
      rating: 7.18,
      votes: 20,
      titles: [
        { title: '奇襲', language: 'ja' },
        { title: 'Surprise Attack', language: 'en' },
        { title: 'Attaque surprise', language: 'fr' },
        { title: 'Kishuu', language: 'x-jat' },
      ],
      summary: null
    },
    {
      id: 1012,
      updatedAt: '2011-07-01',
      episodeNumber: '3',
      type: 1,
      length: 25,
      airDate: '1999-01-17',
      rating: 7.31,
      votes: 19,
      titles: [
        { title: '愛の娘', language: 'ja' },
        { title: 'Daughter of Love', language: 'en' },
        { title: 'La fille d`Amour', language: 'fr' },
        { title: 'Ai no Musume', language: 'x-jat' },
      ],
      summary: null
    },
    {
      id: 1013,
      updatedAt: '2011-07-01',
      episodeNumber: '9',
      type: 1,
      length: 25,
      airDate: '1999-02-28',
      rating: 6.84,
      votes: 17,
      titles: [
        { title: '戦場へ', language: 'ja' },
        { title: 'To the Battlefield', language: 'en' },
        { title: 'Vers le champ de bataille', language: 'fr' },
        { title: 'Senjou e', language: 'x-jat' },
      ],
      summary: null
    },
    {
      id: 1014,
      updatedAt: '2011-07-01',
      episodeNumber: '13',
      type: 1,
      length: 40,
      airDate: '1999-03-28',
      rating: 8.53,
      votes: 16,
      titles: [
        { title: '天翔る迷惑', language: 'ja' },
        { title: 'Trouble Soaring Through Heaven', language: 'en' },
        { title: 'Des gêneurs dans le firmament', language: 'fr' },
        { title: 'Amagakeru Meiwaku', language: 'x-jat' },
      ],
      summary: null
    },
    {
      id: 1015,
      updatedAt: '2011-07-01',
      episodeNumber: '8',
      type: 1,
      length: 25,
      airDate: '1999-02-21',
      rating: 7.19,
      votes: 17,
      titles: [
        { title: 'アーヴの流儀', language: 'ja' },
        { title: 'The Style of the Abh', language: 'en' },
        { title: 'La méthode Abh', language: 'fr' },
        { title: 'Abh no Ryuugi', language: 'x-jat' },
      ],
      summary: null
    },
    {
      id: 1016,
      updatedAt: '2011-07-01',
      episodeNumber: '12',
      type: 1,
      length: 25,
      airDate: '1999-03-21',
      rating: 6.66,
      votes: 17,
      titles: [
        { title: '惑乱の淑女', language: 'ja' },
        { title: 'Lady of Chaos', language: 'en' },
        { title: 'La Dame du Chaos', language: 'fr' },
        { title: 'Wakuran no Shukujo', language: 'x-jat' },
      ],
      summary: null
    },
    {
      id: 1017,
      updatedAt: '2011-07-01',
      episodeNumber: '7',
      type: 1,
      length: 25,
      airDate: '1999-02-14',
      rating: 6.93,
      votes: 17,
      titles: [
        { title: '幸せな叛逆', language: 'ja' },
        { title: 'Fortunate Revolt', language: 'en' },
        { title: 'Heureuse révolte', language: 'fr' },
        { title: 'Shiawase na Hangyaku', language: 'x-jat' },
      ],
      summary: null
    },
    {
      id: 1018,
      updatedAt: '2011-07-01',
      episodeNumber: '11',
      type: 1,
      length: 25,
      airDate: '1999-03-14',
      rating: 5.99,
      votes: 18,
      titles: [
        { title: 'スファグノーフ門沖会戦', language: 'ja' },
        { title: 'Sufugnoff Gateway Battle', language: 'en' },
        { title: 'La bataille du portail de Sfagnaumh', language: 'fr' },
        { title: 'Sufugnoff Mon Oki Kaisen', language: 'x-jat' },
      ],
      summary: null
    },
    {
      id: 1019,
      updatedAt: '2011-07-01',
      episodeNumber: '6',
      type: 1,
      length: 25,
      airDate: '1999-02-07',
      rating: 6.61,
      votes: 17,
      titles: [
        { title: '不可解な陰謀', language: 'ja' },
        { title: 'Mysterious Conspiracy', language: 'en' },
        { title: 'Mystérieuses intrigues', language: 'fr' },
        { title: 'Fukakai na Inbou', language: 'x-jat' },
      ],
      summary: null
    },
    {
      id: 120767,
      updatedAt: '2010-08-05',
      episodeNumber: 'C3',
      type: 3,
      length: 0,
      airDate: undefined,
      rating: 3.81,
      votes: 1,
      titles: [{ title: 'Ending 2', language: 'en' }],
      summary: null
    },
    {
      id: 120768,
      updatedAt: '2010-08-05',
      episodeNumber: 'C2',
      type: 3,
      length: 0,
      airDate: undefined,
      rating: 5.7,
      votes: 1,
      titles: [{ title: 'Ending 1', language: 'en' }],
      summary: null
    },
    {
      id: 120769,
      updatedAt: '2010-08-05',
      episodeNumber: 'C1',
      type: 3,
      length: 0,
      airDate: undefined,
      rating: 3.81,
      votes: 1,
      titles: [{ title: 'Opening', language: 'en' }],
      summary: null
    },
  ],
};
