module.exports = {
  id: 11021,
  ageRestricted: true,
  type: 'OVA',
  episodeCount: 4,
  startDate: '2015-03-27',
  endDate: '2015-08-28',
  titles: [
    { title: 'Mankitsu Happening', language: 'x-jat', type: 'main' },
    { title: '漫喫ハプニング', language: 'ja', type: 'official' },
  ],
  description:
    '* Based on the erotic game by http://anidb.net/cr942 [Waffle].\nHaving just got fired due to his body condition Keiichi gets offered a job at his friend`s manga cafe. Here he meets the long time worker Rei and his childhood friend Kururu. With his condition acting up things quickly spiral out of control.',
  picture: '167298.jpg',
  ratings: {
    permanent: { score: '6.38', count: '274' },
    temporary: { score: '6.93', count: '284' },
    review: { score: undefined, count: undefined },
  },
  related: [],
  similar: [],
  recommendations: [
    {
      type: 'Must See',
      uid: 684759,
      content:
        'This hentai is quite amazing considering it`s animation is quite good and only took a year to complete 4 whole episodes. The series is quite lewd but also displays a lot of absurdist situations that`s hard not to laugh at. Probably the best hentai to come out in the last 5 years.',
    },
  ],
  url: 'http://www.call-it-anything.net/product/mankitu01.html',
  creators: [
    { id: 42565, type: 'Character Design', name: 'Citizen08' },
    { id: 942, type: 'Original Work', name: 'Waffle' },
    { id: 33720, type: 'Direction', name: 'Matano Ryuuzou' },
  ],
  resources: [
    { type: 2, externalEntity: [{ ids: ['29575'], url: undefined }] },
    {
      type: 4,
      externalEntity: [
        { ids: undefined, url: 'http://a1c.jp/~collabo/product/mankitu01.html' },
        { ids: undefined, url: 'http://a1c.jp/~collabo/product/mankitu02.html' },
        { ids: undefined, url: 'http://a1c.jp/~collabo/product/mankitu03.html' },
        { ids: undefined, url: 'http://a1c.jp/~collabo/product/mankitu04.html' },
      ],
    },
    { type: 14, externalEntity: [{ ids: ['14650', 'v'], url: undefined }] },
  ],
  tags: [
    {
      id: 301,
      parentId: 2848,
      weight: 300,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'lactation',
      description: 'Capable of secreting breast milk, sometimes referred to as Mother`s milk.',
      pictureUrl: '176139.jpg',
      updatedAt: '2015-08-10',
    },
    {
      id: 2604,
      parentId: undefined,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'content indicators',
      description:
        'The content indicators branch is intended to be a less geographically specific tool than the `age rating` used by convention, for warning about things that might cause offence. Obviously there is still a degree of subjectivity involved, but hopefully it will prove useful for parents with delicate children, or children with delicate parents.\nRefer to further guidance on http://wiki.anidb.net/w/Categories:Content_Indicators [the Wiki page] for how to apply tag weights for content indicators.',
      pictureUrl: undefined,
      updatedAt: '2018-07-08',
    },
    {
      id: 2606,
      parentId: undefined,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'target audience',
      description:
        'Anime, like everything else in the modern world, is targeted towards specific audiences, both implicitly by the creators and overtly by the marketing. While categories are associated with specific sex and age groups, this is not a bar on the anime being enjoyed by people who don`t fit into that band; not only do crossover titles exist, but the categories also have a considerable following outside their main demographic, and a person might as well enjoy anime from all categories. Still, does not invalidate the usefulness of marking a title as one of the categories; the same themes will likely be treated differently in anime geared for different audiences. Only one should not jump the gun and assume that a title will be more or less serious or present content in this or that way due to its target audience, or conversely assume the target audience on the content and its presentation alone. As such, the audience categories help form a broad impression of how a title might work with the announced themes, but offer little to no in-depth information about specific content or its treatment.\nThe audience categories originate from manga magazines, which group titles of a same intended audience into a magazine that is advertised as belonging to that category, and so manga-based anime will have the category from their parent work. As for anime based on other works, the audience is often debatable, but comparing information such as time slot to the manga-based anime generally helps figure out the most likely possibility.',
      pictureUrl: undefined,
      updatedAt: '2014-10-18',
    },
    {
      id: 2608,
      parentId: undefined,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'fetishes',
      description:
        'Everything under fetishes (except for Bishounen and Juujin) is strictly only meant for hentai (18 Restricted) and ecchi anime. In case of ecchi, it must be the main element of the show and not when there`s only some of it, for example, there`s some ecchi in Shinseiki Evangelion, but the fact you get to see Asuka`s pantsu doesn`t warrant it the schoolgirl fetish category. So be careful to which ecchi show you add fetishes; it`s fairly straightforward with hentai, though. Overall, this category tree is to satisfy the needs of people with different fetishes, so they can search for what tingles their tangle; hence why this is restricted to hentai and full ecchi shows.',
      pictureUrl: undefined,
      updatedAt: '2012-12-04',
    },
    {
      id: 2609,
      parentId: undefined,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'original work',
      description:
        'What the anime is based on! This is given as the original work credit in the OP. Mostly of academic interest, but a useful bit of info, hinting at the possible depth of story.',
      pictureUrl: undefined,
      updatedAt: '2018-09-01',
    },
    {
      id: 2610,
      parentId: undefined,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'setting',
      description:
        'The setting describes in what time and place an anime takes place. To a certain extent it describes what you can expect from the world in the anime.',
      pictureUrl: undefined,
      updatedAt: '2009-04-22',
    },
    {
      id: 2611,
      parentId: undefined,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'elements',
      description:
        'Next to Themes setting the backdrop for the protagonists in anime, there are the more detailed plot Elements that centre on character interactions: "What do characters do to each other or what is done to them?". Is it violent Action, an awe-inspiring Adventure in a foreign place, the gripping life of a Detective, a slapstick Comedy, an Ecchi Harem anime, a SciFi epic, or some Fantasy travelling adventure?',
      pictureUrl: undefined,
      updatedAt: '2014-09-08',
    },
    {
      id: 2612,
      parentId: 2610,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'time',
      description:
        'This placeholder lists different epochs in human history and more vague but important timelines such as the future, the present and the past.',
      pictureUrl: undefined,
      updatedAt: '2016-09-04',
    },
    {
      id: 2613,
      parentId: 2610,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'place',
      description:
        'The places the anime can take place in. Includes more specific places such as a country on Earth, as well as more general places such as a dystopia or a mirror world.',
      pictureUrl: undefined,
      updatedAt: '2016-09-04',
    },
    {
      id: 2615,
      parentId: 2606,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: '18 restricted',
      description:
        'This isn`t really an "audience".\nWhile some anime might feature sexual content they still might not be considered pornography. This category is meant only for when the content is clearly *not* intended for minors. The distinction is made by whether the content is sold only to adults.',
      pictureUrl: '10710.gif',
      updatedAt: '2016-02-27',
    },
    {
      id: 2624,
      parentId: 2612,
      weight: 600,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'present',
      description: 'Somewhere between past and future.',
      pictureUrl: undefined,
      updatedAt: '2017-02-20',
    },
    {
      id: 2630,
      parentId: 2613,
      weight: 600,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'Earth',
      description:
        'The Earth is the third planet from the Sun, and the densest and fifth-largest of the eight planets in the Solar System. It is in effect a ball of hot mud, but on the surface it`s cold enough, so most of us live on it (or are supposed to). It is circa 4.5 billion years old, and, unless we humans succeed in destroying it over the next couple of centuries, it is expected to last for quite another while, though the changes in the Sun`s emissions due to its aging will likely cause the extinction of everything; the species of earthlings are guaranteed to die, even if we fail to kill them -- unless, of course, we find ourselves another planet and figure out a way to take everything there. Our little planet on a corner of this galaxy may mean nothing in the grand scheme of things, but to its inhabitants it is their home, so, as a species, we cherish it dearly, to the point many cultures even to this day deify it. Being the home to the human civilizations, the Earth is the main setting of most fiction, be it anime or otherwise, but not only are many titles set in other places, such as unrelated fantasy worlds, in a considerable number of fictional titles the Earth is actually destroyed by aggressive alien invaders.',
      pictureUrl: '126792.jpg',
      updatedAt: '2012-10-13',
    },
    {
      id: 2672,
      parentId: 2834,
      weight: 600,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'Japan',
      description:
        'Japan is a sovereign island nation in East Asia. Located in the Pacific Ocean, it lies off the eastern coast of the Asian mainland and stretches from the Sea of Okhotsk in the north to the East China Sea and China in the southwest.\nSource: Wikipedia',
      pictureUrl: '65689.png',
      updatedAt: '2018-03-05',
    },
    {
      id: 2695,
      parentId: 2848,
      weight: 200,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'yuri',
      description:
        'Yuri refers to anime that portray lesbian (female/female) sex. Do not confuse this with the http://anidb.net/t2782 [Shoujo Ai] category under Romance, which only portrays girl/girl relationships, but generally not anything pornographic. This is real female/female porn.\nThe male version is http://anidb.net/t2723 [Yaoi].\nhttp://anidb.net/t7146 [Cute girls doing cute things (CGDCT)] is often mistaken as low level Yuri or Shoujo Ai. If there is no Yuri or Shoujo Ai subtext, i.e. if there is no romantic subtext, only tag CGDCT.',
      pictureUrl: '150944.jpg',
      updatedAt: '2018-09-01',
    },
    {
      id: 2696,
      parentId: 2848,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'threesome',
      description:
        'Tag for any scene where sexual acts take place with three people of any gender. Should not be used if more than three.',
      pictureUrl: '150774.jpg',
      updatedAt: '2016-01-13',
    },
    {
      id: 2697,
      parentId: 2848,
      weight: 200,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'voyeurism',
      description:
        'Voyeurism is the sexual interest in or practice of spying on people engaged in intimate behaviors, such as undressing, sexual activity, or other actions usually considered to be of a private nature. The principal characteristic of voyeurism is that the voyeur does not normally interact directly with the subject of his/her interest, who is often unaware of being observed. The essence of voyeurism is the observing but may also involve the making of a secret photograph or video of the subject during an intimate activity. When the interest in a particular subject is obsessive, the behavior may be described as stalking.\nSource: Wikipedia',
      pictureUrl: '162189.jpg',
      updatedAt: '2015-05-05',
    },
    {
      id: 2701,
      parentId: 2848,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'pussy sandwich',
      description:
        'The act of stacking one girl on top of another stomach to stomach and screwing the space in between or just alternating between their pussies.',
      pictureUrl: '161398.jpg',
      updatedAt: '2014-09-21',
    },
    {
      id: 2702,
      parentId: 2848,
      weight: 200,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'mammary intercourse',
      description:
        'Mammary intercourse is a sex act, performed as foreplay or as non-penetrative sex, that involves the stimulation of the male penis by the female breasts. Commonly, this sex act involves the man placing his penis in the woman`s cleavage and thrusting between her breasts, while the breasts are squeezed around the penis for additional stimulation, and fellatio may also be performed in combination. Mammary intercourse is also commonly known as titty-fucking or titfuck in the United States, as well as tit wank or French fuck in the United Kingdom. The Japanese term, paizuri (from oppai, breasts, and the verb suru, used in this context to describe the sexual act), is commonly used in the anime fandom. A variant term is "naizuri" (a pun on nai, the negative of the verb aru, indicating existence/presence), which describes an attempt to do a paizuri, but with insufficient cleavage.',
      pictureUrl: '174692.jpg',
      updatedAt: '2015-06-16',
    },
    {
      id: 2704,
      parentId: 2848,
      weight: 100,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'cum play',
      description:
        'Fetish of sorts where the focus is of the semen that is ejaculated. This can include snowballing, drinking copious amounts of semen, eating it off food, using it to brush one`s teeth, acting as a urinal for semen, gargling it, rinsing one`s mouth with it, or any other act where semen is involved that does not have to do with fertilization of an egg.\nThis should not be used if one cannot visibly see semen in scenes or if the scene is extremely short.',
      pictureUrl: undefined,
      updatedAt: '2014-09-20',
    },
    {
      id: 2705,
      parentId: 2848,
      weight: 600,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'creampie',
      description:
        'The act of a man ejaculating inside a girl`s vagina, leaving the semen oozing out of her.',
      pictureUrl: '160720.jpg',
      updatedAt: '2014-09-20',
    },
    {
      id: 2706,
      parentId: 2848,
      weight: 200,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'masturbation',
      description:
        'Manual erotic stimulation of the genitals or other erogenous regions, often to orgasm, either by oneself or a partner.',
      pictureUrl: '210612.jpg',
      updatedAt: '2017-12-13',
    },
    {
      id: 2707,
      parentId: 2848,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'internal shots',
      description:
        'Internal shots are pictures that display the interior of the body of a living being, either through the skin, kind of as an "x-ray" of sorts, or from the inside, as if the camera was also inside. This is generally used during sex scenes to display the inside of any area being penetrated. Those shots may happen either by making an area of the body transparent or by displaying the same area again, but from the inside; the latter method is shown in the picture.',
      pictureUrl: '213307.jpg',
      updatedAt: '2018-02-20',
    },
    {
      id: 2710,
      parentId: 2848,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'squirting',
      description: 'Squirt, a small, quick stream, a jet when girl gets orgasm.',
      pictureUrl: undefined,
      updatedAt: '2014-09-20',
    },
    {
      id: 2712,
      parentId: 2848,
      weight: 200,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'sex toys',
      description:
        'A sex toy is an object or device that is primarily used to facilitate human sexual pleasure, such as a dildo or vibrator.',
      pictureUrl: undefined,
      updatedAt: '2014-10-22',
    },
    {
      id: 2713,
      parentId: 2848,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'oral',
      description:
        'Oral sex is sexual activity involving the stimulation of the genitalia of a sex partner by the use of the mouth, tongue, teeth or throat.',
      pictureUrl: undefined,
      updatedAt: '2012-10-07',
    },
    {
      id: 2717,
      parentId: 2848,
      weight: 300,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'anal',
      description:
        'Sodomy, buggery, buttsex, cornholing, or the poop-chute polka. Call it whatever you like, but somebody is getting something stuck where the sun does not shine.',
      pictureUrl: '173755.jpg',
      updatedAt: '2016-09-04',
    },
    {
      id: 2721,
      parentId: 2848,
      weight: 400,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'public sex',
      description:
        'Public sex refers to sexual acts that take place in public or semi-public places.',
      pictureUrl: '175406.jpg',
      updatedAt: '2015-07-13',
    },
    {
      id: 2722,
      parentId: 2848,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'doggy style',
      description: 'Bang her from behind and use her boobies as a steering wheel!',
      pictureUrl: '161394.jpg',
      updatedAt: '2014-09-21',
    },
    {
      id: 2724,
      parentId: 2848,
      weight: 200,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'double penetration',
      description:
        'Double penetration is a situation during which someone is simultaneously penetrated by two penises or strap-ons.',
      pictureUrl: '172771.jpg',
      updatedAt: '2015-05-15',
    },
    {
      id: 2725,
      parentId: 2848,
      weight: 600,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'ahegao',
      description:
        'A term for the weird face occasionally seen in adult games/anime/manga. Canonically, ahegao has eyes rolled up, mouth open and tongue sticking out. Sometimes also referred to as "fucked silly".',
      pictureUrl: '175637.jpg',
      updatedAt: '2015-07-20',
    },
    {
      id: 2729,
      parentId: 2848,
      weight: 200,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'BDSM',
      description:
        'A form of "kinky sex". The acronym BDSM derives from BD (bondage and discipline), DS (dominance and submission) and SM (sadism and masochism). BDSM usually characterizes with one side being superior (active) over the other (passive), with each side being one or more participants. Whips, chains, handcuffs, ropes, blindfolds are common elements of BDSM.',
      pictureUrl: undefined,
      updatedAt: '2014-12-09',
    },
    {
      id: 2730,
      parentId: 2848,
      weight: 100,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'exhibitionism',
      description:
        'Exhibitionism is the act of exposing in a public or semi-public context the parts of one`s body that are not normally exposed. That may be done to prompt sexual arousal, but many forms of exhibitionism actually mean to create humour or disparagement through shock value or mockery. The idea of exhibitionism is closely tied to the notions of decency and modesty in dressing, and as such is highly dependent on one`s own cultural background. Certain forms of exhibitionism may be considered indecent exposure, and thus in many jurisdictions they may lead to civil or criminal charges. While both deal with the lack of clothing and may in certain cases overlap, exhibitionism is very different from and not to be confused with http://anidb.net/t2304 [nudism].',
      pictureUrl: '162657.jpg',
      updatedAt: '2014-10-20',
    },
    {
      id: 2741,
      parentId: 2891,
      weight: 600,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'large breasts',
      description:
        'Large breasts are breasts a fair notch larger than average, as found in some adolescent girls or fully grown women; however, as anime has no upper limit to breast size, the definition applies somewhat differently. To be considered large, breasts in anime must be bigger than real-life natural ones or natural-seeming fake ones, to the point they`d appear weirdly or even abnormally large in real-life females. On the high end of the spectrum, breasts that are as big as the character`s head or possibly a bit bigger are still considered large; however, breasts that take at least as much space as the rest of the chest or the abdomen, or that are almost as big but have an absurdly unnatural shape, are the less common http://anidb.net/t1774 [gigantic breasts] instead.',
      pictureUrl: '161014.jpg',
      updatedAt: '2015-12-14',
    },
    {
      id: 2747,
      parentId: 2900,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'hidden vibrator',
      description:
        'This anime features scenes where a character uses or is forced/tricked into using a vibrator in secret during every day activities, for example while at work, at school, eating dinner, etc.',
      pictureUrl: '185953.jpg',
      updatedAt: '2016-04-21',
    },
    {
      id: 2748,
      parentId: 2604,
      weight: 600,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'sex',
      description:
        'Sexual intercourse, the ultimate bond of love and the "Origin of the World" (just think of Gustave Courbet`s painting: http://en.wikipedia.org/wiki/L%27Origine_du_monde).\nRefer to further guidance on http://wiki.anidb.net/w/Categories:Content_Indicators [the Wiki page] for how to apply tag weights for content indicators.',
      pictureUrl: '161190.jpg',
      updatedAt: '2018-07-15',
    },
    {
      id: 2749,
      parentId: 2604,
      weight: 600,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'nudity',
      description:
        'Nudity is the state of wearing no clothing. The wearing of clothing is exclusively a human characteristic. The amount of clothing worn depends on functional considerations (such as a need for warmth or protection from the elements) and social considerations. In some situations the minimum amount of clothing (i.e. covering of a person`s genitals) may be socially acceptable, while in others much more clothing is expected.\nRefer to further guidance on http://wiki.anidb.net/w/Categories:Content_Indicators [the Wiki page] for how to apply tag weights for content indicators.\nPeople, as individuals and in groups, have varying attitudes towards their own nudity. Some people are relaxed about appearing less than fully clothed in front of others, while others are uncomfortable or inhibited in that regard. People are nude in a variety of situations, and whether they are prepared to disrobe in front of others depends on the social context in which the issue arises. For example, people need to bathe without clothing, some people also sleep in the nude, some prefer to sunbathe in the nude or at least topless, while others are nude in other situations. Some people adopt naturism as a lifestyle.\nThough the wearing of clothes is the social norm in most cultures, some cultures, groups and individuals are more relaxed about nudity, though attitudes often depend on context. On the other hand, some people feel uncomfortable in the presence of any nudity, and the presence of a nude person in a public place can give rise to controversy, irrespective of the attitude of the person who is nude. Besides meeting social disapproval, in some places public nudity may constitute a crime of indecent exposure. Many people have strong views on nudity, which to them can involve issues and standards of modesty, decency and morality. Some people have an psychological aversion to nudity, called gymnophobia. Many people regard nudity to be inherently sexual and erotic.\nNudity is to be found in a multitude of media, including art, photography, film and on the Internet. It is a factor in adult entertainment of various types.\nEspecially gratuitous fanservice anime shows tend to show their (usually female) characters frequently without any clothes, though often hiding genitals through the means of additions like steam.\nSource: wiki',
      pictureUrl: '60576.jpg',
      updatedAt: '2018-07-08',
    },
    {
      id: 2800,
      parentId: 2609,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'game',
      description:
        'Based on an interactive (even if minimally so) form of entertainment software, generally available for PCs, consoles or arcade machines.',
      pictureUrl: undefined,
      updatedAt: '2009-04-20',
    },
    {
      id: 2803,
      parentId: 2800,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'erotic game',
      description:
        'An erotic game (eroge) is a Japanese video or computer game that features erotic content, usually in the form of anime-style artwork. In English, eroge are often called hentai games in keeping with the English slang definition of hentai. This is sometimes shortened to H games. In Japan, eroge are also referred to as 18+ games. Most erotic games are visual novels or dating sims but are not limited to them.\nAny anime adaptation of a game that contains (or had a version that contains) adult content (generally sex scenes), regardless of how some fanboys blabber on how "the story in that visual novel was too good to be labelled as porn!", should definitely get this category added under them. This should make it pretty clear as to what is an erotic game and what is not.',
      pictureUrl: undefined,
      updatedAt: '2014-09-07',
    },
    {
      id: 2834,
      parentId: 2630,
      weight: 600,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'Asia',
      description:
        'Asia is Earth`s largest and most populous continent, located primarily in the eastern and northern hemispheres and sharing the continental landmass of Eurasia with the continent of Europe. Asia covers an area of 44,579,000 square kilometers, about 30% of Earth`s total land area and 8.7% of the Earth`s total surface area. The continent, which has long been home to the majority of the human population, was the site of many of the first civilizations. Asia is notable for not only its overall large size and population, but also dense and large settlements as well as vast barely populated regions within the continent of 4.4 billion people.\nSource: Wikipedia',
      pictureUrl: '192245.jpg',
      updatedAt: '2016-10-04',
    },
    {
      id: 2848,
      parentId: 2611,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'pornography',
      description:
        'Anime clearly marked as "Restricted 18" material centring on all variations of adult sex, some of which can be considered as quite perverted. To certain extent, some of the elements can be seen on late night TV animations.',
      pictureUrl: undefined,
      updatedAt: '2018-07-15',
    },
    {
      id: 2856,
      parentId: 2611,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'ecchi',
      description:
        'Fan service is found in many anime, in many forms. When the service has a distinctly sexual slant to it, and it appears to be a major focus of the show, then it`s safe to assume you`re watching ecchi.\nThe word "ecchi" is used by English-speaking anime fans to refer to refer to soft-core pornographic or sexually suggestive anime and manga. This is a western invention; in Japanese, it is a catch-all term for all things anyhow sexual in nature, not being limited to porn, but also not really considered a "milder" term, as it may also refer to sexual intercourse itself. The term "ecchi" in Japanese comes from the pronunciation of the letter "H" in English, which is rendered into Japanese syllabary as エッチ, which in turn is transliterated in the English alphabet as "ecchi" or "etchi". It is not, as many believe, short for "hentai" -- that, too, seems to be a western invention. It is, however, nearly as misunderstood and misapplied a term as "hentai".\nThe line between ecchi and hentai, from the western perspective over these terms, can be hard to draw at times; one good rule of thumb is: if it was aired on Japanese public TV at all, it probably wasn`t hentai. Ecchi usually features all the specifics to human anatomy that can only be found in anime, and generally avoids full nudity, instead abusing of panty shots. Hentai, on the other hand, will usually show full frontal nudity in some explicit form, including genitalia, and full, intimate sex scenes. At its mildest, ecchi is composed of double entendres, big misunderstandings, and sexual farce; at its most explicit, it is still in the realm of softcore pornography, with full breast shots, full back nudity and similar content, but no display of genitalia. Another good way to distinguish the two is looking for animated sex scenes; if one is found, you have generally left the genre entirely, though a few borderline exceptions apply here. For AniDB`s purposes, the distinction between explicit ecchi and actual hentai is simple: if it was sold with a 18+ restriction in its country of origin, it is hentai; if it was sold without it, it is ecchi.\nSource: TV Tropes',
      pictureUrl: '32416.jpg',
      updatedAt: '2014-09-05',
    },
    {
      id: 2859,
      parentId: 2611,
      weight: 600,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'harem',
      description:
        'Harem is an entertainment-related trope which is characterized by three or more characters, normally female, who for some reason are in the presence and under the influence of one character, generally male, according to a few genre-defining guidelines; here it will be assumed, for simplicity of language, that the harem lead is a male character and the members are female characters. Though that is the rule, there are exceptions; a story in which there is one female character and several male characters is normally called a "http://anidb.net/t2792 [reverse harem]", or sometimes also "male harem". Aside from the swapping of the characters` genders, the trope`s details are mostly the same, with the majority of the changes relating to the differences in behavior between men and women of the characters` age range. It is also possible to create harems with homosexual relationships, again with very few changes to the main antics themselves. The harem may not have more than only one lead, as that would be a love polygon, or less than three members, as one would form a couple and two would make a love triangle.\nAs a defining rule of harem, the interactions between the lead and each of the individual members are filled with romantically or sexually loaded content, either implicitly, through innuendo or subtext, or explicitly, through text or actions, and those actions are a key plot element. Generally, the female characters` looks and personalities will vary a lot among the ones present in one single series, but quite rarely will they actually differ from the common stock archetypes, which are known, well-defined, and easy to copy; for this reason, the genre as a whole is often considered repetitive. Usually, the characters involved directly in this trope are in the late teenager to young adult age range, but that is not mandatory. Sexually charged behavior on the lead`s part pretty much can`t be avoided, and it`s typical to see him stamped as a pervert by some or all of the members, regardless of whether he is one; the sexual tones also applies to the depiction of the harem members, often leading the genre to labeled sexist. The lead will often suffer very violent retribution for his behavior, which has attracted criticism of gratuitous violence as well.\nMost of the harem members will be romantically or sometimes sexually interested in the one male character, and in him alone; that, however, is not an absolute rule, and indeed sometimes none of the female characters are really interested at first, so the protagonist has to build relationships with them from scratch. That idea comes in large part from visual novels; it is quite common for visual novels to revolve around controlling the male lead and have him build relationships with either as many female characters as possible or with one of them, the latter being more common for visual novels with branched story paths; a large portion of those visual novels also feature erotic content, which may be hard to adapt to TV series. It may be also possible that the harem is only a support to the existing or predictable relationship between the lead and the most important member; additionally, the lead may end up in relationships with most or all of the harem members, with the agreement of all, in a setting normally called "harem ending".',
      pictureUrl: '94602.jpg',
      updatedAt: '2016-09-04',
    },
    {
      id: 2891,
      parentId: 2608,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'breasts',
      description:
        'The female bust size matters! Or does it? The three subcategories spell out the sizes that relate to fetishes, be they gigantic, large or small. Normal sized breasts are not a fetish, it seems. The tag is not only used for ecchi anime, but also for hentai shows as well.',
      pictureUrl: '161015.jpg',
      updatedAt: '2014-12-31',
    },
    {
      id: 2896,
      parentId: 2608,
      weight: 300,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'deflowering',
      description:
        'Deflowering is the act of breaking the hymen of a female who hadn`t yet had vaginal intercourse. This tag can be applied only to pornographic anime in which a female is seen being deflowered; most often, one knows she had been a virgin because blood is seen coming out of her vagina during sex or after it, but her word on the matter is also considered valid.',
      pictureUrl: undefined,
      updatedAt: '2015-06-23',
    },
    {
      id: 2900,
      parentId: 2712,
      weight: 200,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'dildos - vibrators',
      description: 'These are toys that are used for sexual pleasure.',
      pictureUrl: undefined,
      updatedAt: '2014-09-20',
    },
    {
      id: 2902,
      parentId: 2729,
      weight: 200,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'facesitting',
      description:
        'Facesitting, also known as queening, or kinging, is a sexual practice in which one partner sits on or over the other`s face, typically to allow or force oral-genital or oral-anal contact. It is common for this position to form part of BDSM, involving dominance and submission, though this need not be the case. Within a BDSM or D/S context, facesitting can be an especially intense form of erotic humiliation.',
      pictureUrl: '191151.jpg',
      updatedAt: '2016-09-11',
    },
    {
      id: 2918,
      parentId: 2713,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'cunnilingus',
      description:
        'Cunnilingus is an oral sex act performed on a female. It involves the use by a sex partner of the mouth, lips and tongue to stimulate the female`s clitoris and vulva. A female may receive cunnilingus as part of foreplay before sexual intercourse, or the sex partner may proceed until the female reaches orgasm.\nThe term is derived from the Latin words for the vulva (cunnus) and tongue (lingua).',
      pictureUrl: '161636.jpg',
      updatedAt: '2014-09-24',
    },
    {
      id: 2920,
      parentId: 2713,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'rimming',
      description:
        'Rimming is the act of using one`s tongue on the anus or perineum of another person in order to gain and/or give sexual pleasure.',
      pictureUrl: '165410.jpg',
      updatedAt: '2014-12-03',
    },
    {
      id: 3299,
      parentId: 6268,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'double fellatio',
      description:
        'Double fellatio is when oral sex is performed on the penis simultaneously by two individuals.',
      pictureUrl: '168623.jpg',
      updatedAt: '2016-09-11',
    },
    {
      id: 4046,
      parentId: 2848,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'foursome',
      description: 'When four people have sex with each other at the same time.',
      pictureUrl: undefined,
      updatedAt: '2014-09-15',
    },
    {
      id: 4826,
      parentId: 2848,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'everybody has sex',
      description: undefined,
      pictureUrl: undefined,
      updatedAt: '2008-06-05',
    },
    {
      id: 5915,
      parentId: 2856,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'French kiss',
      description: 'A kiss in which the tongue enters the partner`s mouth.',
      pictureUrl: undefined,
      updatedAt: '2013-11-12',
    },
    {
      id: 6218,
      parentId: 2704,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'gokkun',
      description:
        'Gokkun is a sexual activity in which a person, not necessarily but usually a female, swallows semen directly from a penis or from a container. The Japanese word "gokkun", whose meaning is close to "gulp" in English, is an onomatopoeia resembling the sound made by swallowing.',
      pictureUrl: undefined,
      updatedAt: '2014-10-14',
    },
    {
      id: 6268,
      parentId: 2713,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'fellatio',
      description:
        'Fellatio is oral sex performed upon the penis. It may be performed to induce male orgasm and ejaculation of semen, or it may be used as foreplay prior to sexual intercourse.',
      pictureUrl: '165408.jpg',
      updatedAt: '2014-12-03',
    },
    {
      id: 6455,
      parentId: 2900,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'double-sided dildo',
      description:
        'A regular dildo is inserted by hand. A double-sided dildo is inserted into the penetrating girl`s vagina and held in place there, so that she can penetrate the receiving girl the same way a male would. Not to be confused with a http://anidb.net/t2899 [strapon].',
      pictureUrl: '175704.jpg',
      updatedAt: '2016-09-04',
    },
    {
      id: 6572,
      parentId: 2696,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'FFM threesome',
      description: 'A threesome with two female and one male partner.',
      pictureUrl: '150774.jpg',
      updatedAt: '2016-01-13',
    },
  ],
  characters: [
    {
      id: 39651,
      type: 'cameo appearance in',
      updatedAt: '2012-05-05',
      rating: 7.69,
      votes: 35,
      name: 'Sanjou Maki',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '87205.jpg',
      seiyuu: [],
    },
    {
      id: 41757,
      type: 'cameo appearance in',
      updatedAt: '2012-08-31',
      rating: 7.3,
      votes: 22,
      name: 'Misono Yuki',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '93217.jpg',
      seiyuu: [],
    },
    {
      id: 43825,
      type: 'cameo appearance in',
      updatedAt: '2012-04-26',
      rating: 8.08,
      votes: 40,
      name: 'Roxanne de Desir',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '86533.jpg',
      seiyuu: [],
    },
    {
      id: 43826,
      type: 'cameo appearance in',
      updatedAt: '2012-11-21',
      rating: 8.41,
      votes: 49,
      name: 'Shamsiel Shahar',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '128389.jpg',
      seiyuu: [],
    },
    {
      id: 44334,
      type: 'cameo appearance in',
      updatedAt: '2012-05-05',
      rating: 5.27,
      votes: 2,
      name: 'Sakonji Seiichi',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '87204.jpg',
      seiyuu: [],
    },
    {
      id: 44753,
      type: 'cameo appearance in',
      updatedAt: '2013-01-12',
      rating: 5.85,
      votes: 32,
      name: 'Isis Petrovna Elenskaya',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '130605.jpg',
      seiyuu: [],
    },
    {
      id: 44754,
      type: 'cameo appearance in',
      updatedAt: '2014-12-02',
      rating: 5.86,
      votes: 32,
      name: 'Gladys von Wackenheim',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '128390.jpg',
      seiyuu: [],
    },
    {
      id: 45189,
      type: 'cameo appearance in',
      updatedAt: '2012-05-26',
      rating: 7.25,
      votes: 4,
      name: 'Ryuuto Henge',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '88446.jpg',
      seiyuu: [],
    },
    {
      id: 48411,
      type: 'cameo appearance in',
      updatedAt: '2012-10-16',
      rating: 6.92,
      votes: 15,
      name: 'Hoshino Kotori',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '126939.jpg',
      seiyuu: [],
    },
    {
      id: 48412,
      type: 'cameo appearance in',
      updatedAt: '2012-10-16',
      rating: 7.27,
      votes: 16,
      name: 'Yanagi Ryouko',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '126938.jpg',
      seiyuu: [],
    },
    {
      id: 48413,
      type: 'cameo appearance in',
      updatedAt: '2012-10-16',
      rating: 6,
      votes: 13,
      name: 'Shimizu Misako',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '126937.jpg',
      seiyuu: [],
    },
    {
      id: 48414,
      type: 'cameo appearance in',
      updatedAt: '2012-10-16',
      rating: 3.43,
      votes: 18,
      name: 'Kamishima Aina',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '126941.jpg',
      seiyuu: [],
    },
    {
      id: 48415,
      type: 'cameo appearance in',
      updatedAt: '2012-10-16',
      rating: 6.06,
      votes: 12,
      name: 'Endou Makiko',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '126940.jpg',
      seiyuu: [],
    },
    {
      id: 62255,
      type: 'cameo appearance in',
      updatedAt: '2014-02-01',
      rating: 6.69,
      votes: 6,
      name: 'Inami Misuzu',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '147534.jpg',
      seiyuu: [],
    },
    {
      id: 62258,
      type: 'cameo appearance in',
      updatedAt: '2017-08-19',
      rating: 6.8,
      votes: 9,
      name: 'Yukawa Ayano',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '206318.jpg',
      seiyuu: [],
    },
    {
      id: 72621,
      type: 'main character in',
      updatedAt: '2015-02-11',
      rating: 5.84,
      votes: 8,
      name: 'Hiiragi Kururu',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '168605.jpg',
      seiyuu: [],
    },
    {
      id: 72622,
      type: 'main character in',
      updatedAt: '2015-02-11',
      rating: 7.26,
      votes: 10,
      name: 'Suzukawa Rei',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '168606.jpg',
      seiyuu: [{ id: 28225, picture: '156289.jpg', name: 'Kasumi Ryou' }],
    },
    {
      id: 73073,
      type: 'main character in',
      updatedAt: '2015-02-11',
      rating: 7.98,
      votes: 9,
      name: 'Mitsuki Otona',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '168607.jpg',
      seiyuu: [{ id: 42377, picture: '188563.jpg', name: 'Yuika' }],
    },
    {
      id: 74165,
      type: 'main character in',
      updatedAt: '2015-04-15',
      rating: 4.75,
      votes: 1,
      name: 'Oyamada Keiichi',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '171896.jpg',
      seiyuu: [{ id: 42735, picture: undefined, name: 'Suzukawa Hiro' }],
    },
    {
      id: 74177,
      type: 'appears in',
      updatedAt: '2015-04-11',
      rating: null,
      votes: null,
      name: 'Sunahara Yoshio',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '171758.jpg',
      seiyuu: [],
    },
    {
      id: 74284,
      type: 'cameo appearance in',
      updatedAt: '2015-05-12',
      rating: 5.33,
      votes: 6,
      name: 'Ichinose Yuka',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '173324.jpg',
      seiyuu: [],
    },
    {
      id: 74285,
      type: 'cameo appearance in',
      updatedAt: '2015-05-12',
      rating: 5.87,
      votes: 5,
      name: 'Kamisuura Risa',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '173325.jpg',
      seiyuu: [],
    },
    {
      id: 74286,
      type: 'cameo appearance in',
      updatedAt: '2015-05-12',
      rating: 6.76,
      votes: 4,
      name: 'Sugai Akari',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '173323.jpg',
      seiyuu: [],
    },
    {
      id: 75393,
      type: 'secondary cast in',
      updatedAt: '2015-05-25',
      rating: 6.43,
      votes: 8,
      name: 'Midou Sayaka',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '173833.jpg',
      seiyuu: [{ id: 16006, picture: '75317.jpg', name: 'Kasuga An' }],
    },
    {
      id: 76164,
      type: 'cameo appearance in',
      updatedAt: '2015-07-03',
      rating: 7.57,
      votes: 3,
      name: 'Katie Majima',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '175079.jpg',
      seiyuu: [],
    },
    {
      id: 76165,
      type: 'cameo appearance in',
      updatedAt: '2015-07-03',
      rating: 5.29,
      votes: 3,
      name: 'Shinjou Honoka',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '175076.jpg',
      seiyuu: [],
    },
    {
      id: 76166,
      type: 'cameo appearance in',
      updatedAt: '2015-07-03',
      rating: 6.97,
      votes: 5,
      name: 'Seto Manaka',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '175078.jpg',
      seiyuu: [],
    },
    {
      id: 76167,
      type: 'cameo appearance in',
      updatedAt: '2015-07-03',
      rating: 7.57,
      votes: 3,
      name: 'Takahama Shizuru',
      gender: 'female',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: '175077.jpg',
      seiyuu: [],
    },
  ],
  episodes: [
    {
      id: 165229,
      updatedAt: '2015-01-08',
      episodeNumber: '1',
      type: 1,
      length: 30,
      airDate: '2015-03-27',
      rating: 6.83,
      votes: 7,
      titles: [
        { title: '~女難が空から降ってくる!? 美少女達から身を守れ!~ 編', language: 'ja' },
        {
          title:
            'Woman Troubles out of Nowhere!? Protect Yourself from the Beautiful Ladies! Compilation',
          language: 'en',
        },
        {
          title: 'Jonan ga Sora kara Futtekuru!? Bishoujo-tachi kara Shin o Mamore! Hen',
          language: 'x-jat',
        },
      ],
      summary: null
    },
    {
      id: 165760,
      updatedAt: '2015-02-04',
      episodeNumber: '2',
      type: 1,
      length: 30,
      airDate: '2015-04-24',
      rating: 8.88,
      votes: 6,
      titles: [
        {
          title: '新人アイドルだってラッキースケベ!? 漫喫個室でラブラブハプニング!! 編',
          language: 'ja',
        },
        {
          title:
            'Even New Idols Can Be Lucky Perverts? Lovey-dovey Development at the Manga Cafe! Chapter',
          language: 'en',
        },
        {
          title: 'Shinjin Idol Datte Lucky Sukebe!? Mankitsu Koshitsu de Love Love Happening!! Hen',
          language: 'x-jat',
        },
      ],
      summary: null
    },
    {
      id: 168309,
      updatedAt: '2015-05-07',
      episodeNumber: '3',
      type: 1,
      length: 30,
      airDate: '2015-07-31',
      rating: 8.1,
      votes: 3,
      titles: [
        { title: 'ラッキースケベ, 危うし!! 社長令嬢が差し出すのは捜査令状!?編', language: 'ja' },
        {
          title:
            'Lucky Pervert Is in Danger! The President`s Daughter Is Getting a Search Warrant!? Chapter',
          language: 'en',
        },
        {
          title: 'Lucky Sukebe, Ayaushi!! Shachou Reijou ga Sashidasu no wa Sousa Reijou!? Hen',
          language: 'x-jat',
        },
      ],
      summary: null
    },
    {
      id: 168843,
      updatedAt: '2015-06-03',
      episodeNumber: '4',
      type: 1,
      length: 30,
      airDate: '2015-08-28',
      rating: 5.2,
      votes: 3,
      titles: [
        {
          title: 'ツンツンデレデレSとMのホライゾン. 爆乳おバカ令嬢はアブノーマルがお好き!?編',
          language: 'ja',
        },
        {
          title:
            'Tsun Tsun Dere Dere. The Horizon of S and M. "Do You Like Big Breasted Stupid Daughters!?" Chapter',
          language: 'en',
        },
        {
          title:
            'Tsuntsun Deredere S to M no Horizon. Bakunyuu Obaka Reijou wa Abnormal ga Osuki!? Hen',
          language: 'x-jat',
        },
      ],
      summary: null
    },
  ],
};
