module.exports = {
  id: 2322,
  ageRestricted: false,
  type: 'TV Series',
  episodeCount: 68,
  startDate: '2001-10-07',
  endDate: '2003-01-26',
  titles: [
    { title: 'Gekitou! Crush Gear Turbo', language: 'x-jat', type: 'main' },
    { title: 'Fight! Crash Gear TURBO', language: 'en', type: 'synonym' },
    { title: 'Fight! Crush Gear TURBO', language: 'en', type: 'synonym' },
    { title: '激闘! クラッシュギアTURBO', language: 'ja', type: 'official' },
    { title: 'Crush Gear Turbo', language: 'de', type: 'official' },
    { title: 'كرش جير', language: 'ar', type: 'official' },
  ],
  description:
    'Marino Kouya is a 5th grade boy who loves Gear Fighting - a sport involving ring battles between small mechanical vehicles. His brother Yuhya had been the Asian Cup Gear Fighter Champion before he died in an accident four years ago. However, Kouya`s skills are nowhere near his brother`s, and one day most of his team members shift to Manganji Club - a team created by his former teammate Manganji Takeshi. As a result, his big brother`s Crush Gear Club faces the threat of closure. Refusing to give up, Kouya offers a challenge to Takeshi and tries to find a way to reinstate the club back to its former glory.\nSource: Wikipedia',
  picture: '58376.jpg',
  ratings: {
    permanent: { score: '3.37', count: '67' },
    temporary: { score: '5.97', count: '70' },
    review: { score: undefined, count: undefined },
  },
  related: [
    { id: 714, type: 'Sequel', name: 'Crush Gear Nitro' },
    { id: 2323, type: 'Sequel', name: 'Gekitou! Crush Gear Turbo: Kaizabaan no Chousen' },
  ],
  similar: [],
  recommendations: [],
  url: 'http://www.sunrise-anime.jp/sunrise-inc/works/detail.php?cid=71',
  creators: [
    { id: 726, type: 'Work', name: 'Sunrise' },
    { id: 3413, type: 'Character Design', name: 'Tobe Atsuo' },
    { id: 5155, type: 'Chief Direction', name: 'Iuchi Shuuji' },
    { id: 1352, type: 'Original Work', name: 'Yatate Hajime' },
    { id: 1071, type: 'Work', name: 'Tokyu Agency' },
    { id: 1019, type: 'Work', name: 'Nagoya TV Housou' },
    { id: 657, type: 'Series Composition', name: 'Gobu Fuyunori' },
    { id: 6665, type: 'Series Composition', name: 'Kitajima Hiroaki' },
  ],
  resources: [
    { type: 1, externalEntity: [{ ids: ['2169'], url: undefined }] },
    { type: 2, externalEntity: [{ ids: ['3012'], url: undefined }] },
    {
      type: 4,
      externalEntity: [{ ids: undefined, url: 'http://sunrise-inc.co.jp/work/detail.php?cid=71' }],
    },
    { type: 6, externalEntity: [{ ids: ['Crush_Gear_Turbo'], url: undefined }] },
    { type: 7, externalEntity: [{ ids: ['激闘!クラッシュギアTURBO'], url: undefined }] },
    { type: 9, externalEntity: [{ ids: ['236340'], url: undefined }] },
    { type: 10, externalEntity: [{ ids: ['4943'], url: undefined }] },
  ],
  tags: [
    {
      id: 922,
      parentId: 2606,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'shounen',
      description:
        'In the context of manga and associated media, shounen, literally meaning "youth" and often also specifically "boy", refers to a male audience roughly between the ages of 10 and 18.\nSource: Wikipedia',
      pictureUrl: undefined,
      updatedAt: '2015-02-04',
    },
    {
      id: 2606,
      parentId: undefined,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'target audience',
      description:
        'Anime, like everything else in the modern world, is targeted towards specific audiences, both implicitly by the creators and overtly by the marketing. While categories are associated with specific sex and age groups, this is not a bar on the anime being enjoyed by people who don`t fit into that band; not only do crossover titles exist, but the categories also have a considerable following outside their main demographic, and a person might as well enjoy anime from all categories. Still, does not invalidate the usefulness of marking a title as one of the categories; the same themes will likely be treated differently in anime geared for different audiences. Only one should not jump the gun and assume that a title will be more or less serious or present content in this or that way due to its target audience, or conversely assume the target audience on the content and its presentation alone. As such, the audience categories help form a broad impression of how a title might work with the announced themes, but offer little to no in-depth information about specific content or its treatment.\nThe audience categories originate from manga magazines, which group titles of a same intended audience into a magazine that is advertised as belonging to that category, and so manga-based anime will have the category from their parent work. As for anime based on other works, the audience is often debatable, but comparing information such as time slot to the manga-based anime generally helps figure out the most likely possibility.',
      pictureUrl: undefined,
      updatedAt: '2014-10-18',
    },
    {
      id: 2610,
      parentId: undefined,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'setting',
      description:
        'The setting describes in what time and place an anime takes place. To a certain extent it describes what you can expect from the world in the anime.',
      pictureUrl: undefined,
      updatedAt: '2009-04-22',
    },
    {
      id: 2612,
      parentId: 2610,
      weight: 0,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'time',
      description:
        'This placeholder lists different epochs in human history and more vague but important timelines such as the future, the present and the past.',
      pictureUrl: undefined,
      updatedAt: '2016-09-04',
    },
    {
      id: 2624,
      parentId: 2612,
      weight: 500,
      localSpoiler: false,
      globalSpoiler: false,
      name: 'present',
      description: 'Somewhere between past and future.',
      pictureUrl: undefined,
      updatedAt: '2017-02-20',
    },
  ],
  characters: [
    {
      id: 28986,
      type: 'secondary cast in',
      updatedAt: '2011-02-20',
      rating: null,
      votes: null,
      name: 'Wang Hu',
      gender: 'male',
      characterType: { id: 1, name: 'Character' },
      description: undefined,
      picture: undefined,
      seiyuu: [{ id: 1934, picture: '186186.jpg', name: 'Aida Sayaka' }],
    },
  ],
  episodes: [
    {
      id: 60446,
      updatedAt: '2006-08-15',
      episodeNumber: '1',
      type: 1,
      length: 25,
      airDate: '2001-10-07',
      rating: 8.6,
      votes: 1,
      titles: [
        { title: '燃えろ!ギアファイト魂', language: 'ja' },
        { title: 'Episode 1', language: 'en' },
        { title: 'Rettung in letzter Minute', language: 'de' },
        { title: 'Moero! Gear Fight Tamashii', language: 'x-jat' },
      ],
    },
    {
      id: 60447,
      updatedAt: '2006-08-15',
      episodeNumber: '2',
      type: 1,
      length: 25,
      airDate: '2001-10-14',
      rating: null,
      votes: null,
      titles: [
        { title: 'あんぱんファイターを探せ!', language: 'ja' },
        { title: 'Episode 2', language: 'en' },
        { title: 'Das Duell', language: 'de' },
        { title: 'Anpan Fighter o Sagase!', language: 'x-jat' },
      ],
    },
    {
      id: 60448,
      updatedAt: '2006-08-15',
      episodeNumber: '3',
      type: 1,
      length: 25,
      airDate: '2001-10-21',
      rating: null,
      votes: null,
      titles: [
        { title: '天才ギアマスタージン', language: 'ja' },
        { title: 'Episode 3', language: 'en' },
        { title: 'Master Jinn', language: 'de' },
        { title: 'Tensai Gear Master Jin', language: 'x-jat' },
      ],
    },
    {
      id: 60449,
      updatedAt: '2006-08-15',
      episodeNumber: '4',
      type: 1,
      length: 25,
      airDate: '2001-10-28',
      rating: null,
      votes: null,
      titles: [
        { title: '4人目のファイター', language: 'ja' },
        { title: 'Episode 4', language: 'en' },
        { title: 'Die unschlagbaren Zwei', language: 'de' },
        { title: '4 Hitome no Fighter', language: 'x-jat' },
      ],
    },
    {
      id: 60450,
      updatedAt: '2006-08-15',
      episodeNumber: '5',
      type: 1,
      length: 25,
      airDate: '2001-11-04',
      rating: null,
      votes: null,
      titles: [
        { title: 'トビタクラブの危機', language: 'ja' },
        { title: 'Episode 5', language: 'en' },
        { title: 'Club der Lügner', language: 'de' },
        { title: 'Tobita Club no Kiki', language: 'x-jat' },
      ],
    },
    {
      id: 60451,
      updatedAt: '2006-08-15',
      episodeNumber: '6',
      type: 1,
      length: 25,
      airDate: '2001-11-11',
      rating: null,
      votes: null,
      titles: [
        { title: 'ギアを賭けたファイト', language: 'ja' },
        { title: 'Episode 6', language: 'en' },
        { title: 'Garuda Eagle in Gefahr', language: 'de' },
        { title: 'Gear o Kaketa Fight', language: 'x-jat' },
      ],
    },
    {
      id: 60452,
      updatedAt: '2006-08-15',
      episodeNumber: '7',
      type: 1,
      length: 25,
      airDate: '2001-11-18',
      rating: null,
      votes: null,
      titles: [
        { title: '兄からの贈り物', language: 'ja' },
        { title: 'Episode 7', language: 'en' },
        { title: 'Das Vermächtnis', language: 'de' },
        { title: 'Ani kara no Okurimono', language: 'x-jat' },
      ],
    },
    {
      id: 60453,
      updatedAt: '2006-08-15',
      episodeNumber: '8',
      type: 1,
      length: 25,
      airDate: '2001-11-25',
      rating: null,
      votes: null,
      titles: [
        { title: 'タコ焼きバトルロイヤル!', language: 'ja' },
        { title: 'Episode 8', language: 'en' },
        { title: 'Das Betrügerteam', language: 'de' },
        { title: 'Takoyaki Battle Royal!', language: 'x-jat' },
      ],
    },
    {
      id: 60454,
      updatedAt: '2006-08-15',
      episodeNumber: '9',
      type: 1,
      length: 25,
      airDate: '2001-12-02',
      rating: null,
      votes: null,
      titles: [
        { title: 'ジロウの古傷', language: 'ja' },
        { title: 'Episode 9', language: 'en' },
        { title: 'Alte Wunden', language: 'de' },
        { title: 'Jirou no Furukizu', language: 'x-jat' },
      ],
    },
    {
      id: 60455,
      updatedAt: '2006-08-15',
      episodeNumber: '10',
      type: 1,
      length: 25,
      airDate: '2001-12-09',
      rating: null,
      votes: null,
      titles: [
        { title: '天才は天才を呼ぶ!', language: 'ja' },
        { title: 'Episode 10', language: 'en' },
        { title: 'Meister gegen Meister', language: 'de' },
        { title: 'Tensai wa Tensai o Yobu!', language: 'x-jat' },
      ],
    },
    {
      id: 60456,
      updatedAt: '2006-08-15',
      episodeNumber: '11',
      type: 1,
      length: 25,
      airDate: '2001-12-16',
      rating: null,
      votes: null,
      titles: [
        { title: '勝利への執念', language: 'ja' },
        { title: 'Episode 11', language: 'en' },
        { title: 'Der Billard-Champ', language: 'de' },
        { title: 'Shouri e no Shuunen', language: 'x-jat' },
      ],
    },
    {
      id: 60457,
      updatedAt: '2006-08-15',
      episodeNumber: '12',
      type: 1,
      length: 25,
      airDate: '2001-12-23',
      rating: null,
      votes: null,
      titles: [
        { title: '史上最強のギア鎧輝', language: 'ja' },
        { title: 'Episode 12', language: 'en' },
        { title: 'Der Adler stürzt ab', language: 'de' },
        { title: 'Shijou Saikyou no Gear Gaiki', language: 'x-jat' },
      ],
    },
    {
      id: 60458,
      updatedAt: '2006-08-15',
      episodeNumber: '13',
      type: 1,
      length: 25,
      airDate: '2001-12-30',
      rating: null,
      votes: null,
      titles: [
        { title: '友情とライバル', language: 'ja' },
        { title: 'Episode 13', language: 'en' },
        { title: 'Die Ehrenbezeugung', language: 'de' },
        { title: 'Yuujou to Rival', language: 'x-jat' },
      ],
    },
    {
      id: 60459,
      updatedAt: '2006-08-15',
      episodeNumber: '14',
      type: 1,
      length: 25,
      airDate: '2002-01-06',
      rating: null,
      votes: null,
      titles: [
        { title: 'マンガンジの野望', language: 'ja' },
        { title: 'Episode 14', language: 'en' },
        { title: 'Der Hokkaido-Cup', language: 'de' },
        { title: 'Manganji no Yabou', language: 'x-jat' },
      ],
    },
    {
      id: 60460,
      updatedAt: '2006-08-15',
      episodeNumber: '15',
      type: 1,
      length: 25,
      airDate: '2002-01-13',
      rating: null,
      votes: null,
      titles: [
        { title: '北の国の剣豪武蔵!', language: 'ja' },
        { title: 'Episode 15', language: 'en' },
        { title: 'In der Höhle des Löwen', language: 'de' },
        { title: 'Kita no Kuni no Kengou Takekura!', language: 'x-jat' },
      ],
    },
    {
      id: 60461,
      updatedAt: '2006-08-15',
      episodeNumber: '16',
      type: 1,
      length: 25,
      airDate: '2002-01-20',
      rating: null,
      votes: null,
      titles: [
        { title: 'それぞれの闘い!', language: 'ja' },
        { title: 'Episode 16', language: 'en' },
        { title: 'Rache!', language: 'de' },
        { title: 'Sorezore no Tatakai!', language: 'x-jat' },
      ],
    },
    {
      id: 60462,
      updatedAt: '2006-08-15',
      episodeNumber: '17',
      type: 1,
      length: 25,
      airDate: '2002-01-27',
      rating: null,
      votes: null,
      titles: [
        { title: '恐怖のイリュージョンカップ!', language: 'ja' },
        { title: 'Episode 17', language: 'en' },
        { title: 'Sieg oder Kuss', language: 'de' },
        { title: 'Kyoufu no Illusion Cup!', language: 'x-jat' },
      ],
    },
    {
      id: 60463,
      updatedAt: '2006-08-15',
      episodeNumber: '18',
      type: 1,
      length: 25,
      airDate: '2002-02-03',
      rating: null,
      votes: null,
      titles: [
        { title: 'ガルダイーグルに吹く風', language: 'ja' },
        { title: 'Episode 18', language: 'en' },
        { title: 'Kampf um Kouya', language: 'de' },
        { title: 'Garuda Eagle ni Fuku Kaze', language: 'x-jat' },
      ],
    },
    {
      id: 60464,
      updatedAt: '2006-08-15',
      episodeNumber: '19',
      type: 1,
      length: 25,
      airDate: '2002-02-10',
      rating: null,
      votes: null,
      titles: [
        { title: 'タコヤキングの逆襲!', language: 'ja' },
        { title: 'Episode 19', language: 'en' },
        { title: 'Die Müll-Attacke', language: 'de' },
        { title: 'Takoyaking no Gyakushuu!', language: 'x-jat' },
      ],
    },
    {
      id: 60465,
      updatedAt: '2006-08-15',
      episodeNumber: '20',
      type: 1,
      length: 25,
      airDate: '2002-02-17',
      rating: null,
      votes: null,
      titles: [
        { title: '翔べ!ガルダイーグル!!', language: 'ja' },
        { title: 'Episode 20', language: 'en' },
        { title: 'Das Finale', language: 'de' },
        { title: 'Tobe! Garuda Eagle!!', language: 'x-jat' },
      ],
    },
    {
      id: 60466,
      updatedAt: '2006-08-15',
      episodeNumber: '21',
      type: 1,
      length: 25,
      airDate: '2002-02-24',
      rating: null,
      votes: null,
      titles: [
        { title: 'トビタクラブ大進撃!', language: 'ja' },
        { title: 'Episode 21', language: 'en' },
        { title: 'Die Entscheidung', language: 'de' },
        { title: 'Tobita Club Daishingeki!', language: 'x-jat' },
      ],
    },
    {
      id: 60467,
      updatedAt: '2006-08-15',
      episodeNumber: '22',
      type: 1,
      length: 25,
      airDate: '2002-03-03',
      rating: null,
      votes: null,
      titles: [
        { title: '哀しみの勝利', language: 'ja' },
        { title: 'Episode 22', language: 'en' },
        { title: 'Totalschaden', language: 'de' },
        { title: 'Kanashimi no Shouri', language: 'x-jat' },
      ],
    },
    {
      id: 60468,
      updatedAt: '2006-08-15',
      episodeNumber: '23',
      type: 1,
      length: 25,
      airDate: '2002-03-10',
      rating: null,
      votes: null,
      titles: [
        { title: 'その一点をねらえ!', language: 'ja' },
        { title: 'Episode 23', language: 'en' },
        { title: 'Das Ziel', language: 'de' },
        { title: 'Sono Itten o Nerae!', language: 'x-jat' },
      ],
    },
    {
      id: 60469,
      updatedAt: '2006-08-15',
      episodeNumber: '24',
      type: 1,
      length: 25,
      airDate: '2002-03-17',
      rating: null,
      votes: null,
      titles: [
        { title: '悔いなき一投!', language: 'ja' },
        { title: 'Episode 24', language: 'en' },
        { title: 'Der große Abschied', language: 'de' },
        { title: 'Kuinaki Ittou!', language: 'x-jat' },
      ],
    },
    {
      id: 60470,
      updatedAt: '2006-08-15',
      episodeNumber: '25',
      type: 1,
      length: 25,
      airDate: '2002-03-24',
      rating: null,
      votes: null,
      titles: [
        { title: '友よ, 激闘の果てに!', language: 'ja' },
        { title: 'Episode 25', language: 'en' },
        { title: 'Böses Erwachen', language: 'de' },
        { title: 'Tomo yo, Gekitou no Hate ni!', language: 'x-jat' },
      ],
    },
    {
      id: 60471,
      updatedAt: '2006-08-15',
      episodeNumber: '26',
      type: 1,
      length: 25,
      airDate: '2002-03-31',
      rating: null,
      votes: null,
      titles: [
        { title: '誕生!ガルダフェニックス!', language: 'ja' },
        { title: 'Episode 26', language: 'en' },
        { title: 'Garuda Phönix', language: 'de' },
        { title: 'Tanjou! Garuda Phoenix!', language: 'x-jat' },
      ],
    },
    {
      id: 60472,
      updatedAt: '2006-08-15',
      episodeNumber: '27',
      type: 1,
      length: 25,
      airDate: '2002-04-07',
      rating: null,
      votes: null,
      titles: [
        { title: 'コウヤ対ハイパーじいちゃん!', language: 'ja' },
        { title: 'Episode 27', language: 'en' },
        { title: 'Die glückliche Begegnung', language: 'de' },
        { title: 'Kouya Tai Hyper Jii-chan!', language: 'x-jat' },
      ],
    },
    {
      id: 60473,
      updatedAt: '2006-08-15',
      episodeNumber: '28',
      type: 1,
      length: 25,
      airDate: '2002-04-14',
      rating: null,
      votes: null,
      titles: [
        { title: '新たなるライバル王虎[ワンフー]!', language: 'ja' },
        { title: 'Episode 28', language: 'en' },
        { title: 'Die Höhle des Löwen', language: 'de' },
        { title: 'Aratanaru Rival Wang Hu!', language: 'x-jat' },
      ],
    },
    {
      id: 60474,
      updatedAt: '2006-08-15',
      episodeNumber: '29',
      type: 1,
      length: 25,
      airDate: '2002-04-21',
      rating: null,
      votes: null,
      titles: [
        { title: '開幕!アジアカップ', language: 'ja' },
        { title: 'Episode 29', language: 'en' },
        { title: 'Offene Rechnungen', language: 'de' },
        { title: 'Kaimaku! Asia Cup', language: 'x-jat' },
      ],
    },
    {
      id: 60475,
      updatedAt: '2006-08-15',
      episodeNumber: '30',
      type: 1,
      length: 25,
      airDate: '2002-04-28',
      rating: null,
      votes: null,
      titles: [
        { title: '唸れ!ビートルダッシュ!!', language: 'ja' },
        { title: 'Episode 30', language: 'en' },
        { title: 'Das Paket', language: 'de' },
        { title: 'Unare! Beetle Dash!!', language: 'x-jat' },
      ],
    },
    {
      id: 60476,
      updatedAt: '2006-08-15',
      episodeNumber: '31',
      type: 1,
      length: 25,
      airDate: '2002-05-05',
      rating: null,
      votes: null,
      titles: [
        { title: 'ブラックガルダの謎', language: 'ja' },
        { title: 'Episode 31', language: 'en' },
        { title: 'Der schwarze Abt', language: 'de' },
        { title: 'Black Garuda no Nazo', language: 'x-jat' },
      ],
    },
    {
      id: 60477,
      updatedAt: '2006-08-15',
      episodeNumber: '32',
      type: 1,
      length: 25,
      airDate: '2002-05-12',
      rating: null,
      votes: null,
      titles: [
        { title: '時を駈ける絆', language: 'ja' },
        { title: 'Episode 32', language: 'en' },
        { title: 'Claudes Geschichte', language: 'de' },
        { title: 'Toki o Kakeru Kizuna', language: 'x-jat' },
      ],
    },
    {
      id: 60478,
      updatedAt: '2006-08-15',
      episodeNumber: '33',
      type: 1,
      length: 25,
      airDate: '2002-05-19',
      rating: null,
      votes: null,
      titles: [
        { title: '激突!鳳凰[ガルダフェニックス]VS猛虎[タイガレイド]', language: 'ja' },
        { title: 'Episode 33', language: 'en' },
        { title: 'Der falsche Freund', language: 'de' },
        { title: 'Gekitotsu! Garuda Phoenix vs Tigeraid', language: 'x-jat' },
      ],
    },
    {
      id: 60479,
      updatedAt: '2006-08-15',
      episodeNumber: '34',
      type: 1,
      length: 25,
      airDate: '2002-05-26',
      rating: null,
      votes: null,
      titles: [
        { title: '究極のファイター!万願寺三凱将!', language: 'ja' },
        { title: 'Episode 34', language: 'en' },
        { title: 'Der Talisman', language: 'de' },
        { title: 'Kyuukyoku no Fighter! Manganji Sangaishou!', language: 'x-jat' },
      ],
    },
    {
      id: 60480,
      updatedAt: '2006-08-15',
      episodeNumber: '35',
      type: 1,
      length: 25,
      airDate: '2002-06-02',
      rating: null,
      votes: null,
      titles: [
        { title: '宿命の対決!アジアカップ最終決戦!', language: 'ja' },
        { title: 'Episode 35', language: 'en' },
        { title: 'Alles oder Nichts', language: 'de' },
        { title: 'Shukumei no Taiketsu! Asia Cup Saishuu Kessen!', language: 'x-jat' },
      ],
    },
    {
      id: 60481,
      updatedAt: '2006-08-15',
      episodeNumber: '36',
      type: 1,
      length: 25,
      airDate: '2002-06-09',
      rating: null,
      votes: null,
      titles: [
        { title: 'アジアカップTODAYスペシャル!', language: 'ja' },
        { title: 'Episode 36', language: 'en' },
        { title: 'Auf Sendung', language: 'de' },
        { title: 'Asia Cup Today Special!', language: 'x-jat' },
      ],
    },
    {
      id: 60482,
      updatedAt: '2006-08-15',
      episodeNumber: '37',
      type: 1,
      length: 25,
      airDate: '2002-06-23',
      rating: null,
      votes: null,
      titles: [
        { title: '忍者ファイター見参!', language: 'ja' },
        { title: 'Episode 37', language: 'en' },
        { title: 'Die Siegesfeier', language: 'de' },
        { title: 'Ninja Fighter Kenzan!', language: 'x-jat' },
      ],
    },
    {
      id: 60483,
      updatedAt: '2006-08-15',
      episodeNumber: '38',
      type: 1,
      length: 25,
      airDate: '2002-06-30',
      rating: null,
      votes: null,
      titles: [
        { title: 'ガルダイーグルを作った男', language: 'ja' },
        { title: 'Episode 38', language: 'en' },
        { title: 'Zwiespältige Gefühle', language: 'de' },
        { title: 'Garuda Eagle o Tsukutta Otoko', language: 'x-jat' },
      ],
    },
    {
      id: 60484,
      updatedAt: '2006-08-15',
      episodeNumber: '39',
      type: 1,
      length: 25,
      airDate: '2002-07-07',
      rating: null,
      votes: null,
      titles: [
        { title: 'バルト海の荒鷲ガレン!', language: 'ja' },
        { title: 'Episode 39', language: 'en' },
        { title: 'Die Lehrstunde', language: 'de' },
        { title: 'Balt-kai no Arawashi Gallen!', language: 'x-jat' },
      ],
    },
    {
      id: 60485,
      updatedAt: '2006-08-15',
      episodeNumber: '40',
      type: 1,
      length: 25,
      airDate: '2002-07-14',
      rating: null,
      votes: null,
      titles: [
        { title: '決闘!クラッシュ巌流島', language: 'ja' },
        { title: 'Episode 40', language: 'en' },
        { title: 'Der Einsiedler', language: 'de' },
        { title: 'Kettou! Crush Ganryuu-jima', language: 'x-jat' },
      ],
    },
    {
      id: 60486,
      updatedAt: '2006-08-15',
      episodeNumber: '41',
      type: 1,
      length: 25,
      airDate: '2002-07-21',
      rating: null,
      votes: null,
      titles: [
        { title: 'ワールドカップ 新たなる戦い!', language: 'ja' },
        { title: 'Episode 41', language: 'en' },
        { title: 'Die Weltmeisterschaft', language: 'de' },
        { title: 'World Cup Aratanaru Tatakai!', language: 'x-jat' },
      ],
    },
    {
      id: 60487,
      updatedAt: '2006-08-15',
      episodeNumber: '42',
      type: 1,
      length: 25,
      airDate: '2002-07-28',
      rating: null,
      votes: null,
      titles: [
        { title: '華麗なる白い騎士団[ヴァイスリッターズ]', language: 'ja' },
        { title: 'Episode 42', language: 'en' },
        { title: 'Die edlen weißen Ritter', language: 'de' },
        { title: 'Karei Naru Weiss Ritters', language: 'x-jat' },
      ],
    },
    {
      id: 60488,
      updatedAt: '2006-08-15',
      episodeNumber: '43',
      type: 1,
      length: 25,
      airDate: '2002-08-04',
      rating: null,
      votes: null,
      titles: [
        { title: '絆に結ばれたファイト!', language: 'ja' },
        { title: 'Episode 43', language: 'en' },
        { title: 'Doppelter Einsatz', language: 'de' },
        { title: 'Kizuna ni Musubareta Fight!', language: 'x-jat' },
      ],
    },
    {
      id: 60489,
      updatedAt: '2006-08-15',
      episodeNumber: '44',
      type: 1,
      length: 25,
      airDate: '2002-08-11',
      rating: null,
      votes: null,
      titles: [
        { title: '発動!恐怖の虎超氷撃[フーチャオピンジー]!!', language: 'ja' },
        { title: 'Episode 44', language: 'en' },
        { title: 'Das Geheimnis um U-Ya', language: 'de' },
        { title: 'Hatsudou! Kyoufu no Huchaobingji!!', language: 'x-jat' },
      ],
    },
    {
      id: 60490,
      updatedAt: '2006-08-15',
      episodeNumber: '45',
      type: 1,
      length: 25,
      airDate: '2002-08-18',
      rating: null,
      votes: null,
      titles: [
        { title: '受け継がれるもの', language: 'ja' },
        { title: 'Episode 45', language: 'en' },
        { title: 'Ein teuflischer Auftrag', language: 'de' },
        { title: 'Uketsugareru Mono', language: 'x-jat' },
      ],
    },
    {
      id: 60491,
      updatedAt: '2006-08-15',
      episodeNumber: '46',
      type: 1,
      length: 25,
      airDate: '2002-08-25',
      rating: null,
      votes: null,
      titles: [
        { title: 'U-YAの秘密', language: 'ja' },
        { title: 'Episode 46', language: 'en' },
        { title: 'Carlos', language: 'de' },
        { title: 'U-YA no Himitsu', language: 'x-jat' },
      ],
    },
    {
      id: 60492,
      updatedAt: '2006-08-15',
      episodeNumber: '47',
      type: 1,
      length: 25,
      airDate: '2002-09-01',
      rating: null,
      votes: null,
      titles: [
        { title: 'タイガフレアの涙', language: 'ja' },
        { title: 'Episode 47', language: 'en' },
        { title: 'Jin gegen Lan', language: 'de' },
        { title: 'Tiger Flare no Namida', language: 'x-jat' },
      ],
    },
    {
      id: 60493,
      updatedAt: '2006-08-15',
      episodeNumber: '48',
      type: 1,
      length: 25,
      airDate: '2002-09-08',
      rating: null,
      votes: null,
      titles: [
        { title: '荒鷲グリフィード, 再び!', language: 'ja' },
        { title: 'Episode 48', language: 'en' },
        { title: 'Die bittere Wahrheit', language: 'de' },
        { title: 'Arawashi Grifeed, Futatabi!', language: 'x-jat' },
      ],
    },
    {
      id: 60494,
      updatedAt: '2006-08-15',
      episodeNumber: '49',
      type: 1,
      length: 25,
      airDate: '2002-09-15',
      rating: null,
      votes: null,
      titles: [
        { title: '憎しみの黒き不死鳥[フェニックス]', language: 'ja' },
        { title: 'Episode 49', language: 'en' },
        { title: 'Hass im Herzen', language: 'de' },
        { title: 'Nikushimi no Kuroki Phoenix', language: 'x-jat' },
      ],
    },
    {
      id: 60495,
      updatedAt: '2006-08-15',
      episodeNumber: '50',
      type: 1,
      length: 25,
      airDate: '2002-09-22',
      rating: null,
      votes: null,
      titles: [
        { title: '破壊貴公子ケイン', language: 'ja' },
        { title: 'Episode 50', language: 'en' },
        { title: 'Der Prinz der Zerstörung', language: 'de' },
        { title: 'Hakai Kikoushi Cain', language: 'x-jat' },
      ],
    },
    {
      id: 60496,
      updatedAt: '2006-08-15',
      episodeNumber: '51',
      type: 1,
      length: 25,
      airDate: '2002-09-29',
      rating: null,
      votes: null,
      titles: [
        { title: '疾風のアークキャバリアー!', language: 'ja' },
        { title: 'Episode 51', language: 'en' },
        { title: 'Kanes Geschichte', language: 'de' },
        { title: 'Shippuu no Ark Cavalier!', language: 'x-jat' },
      ],
    },
    {
      id: 60497,
      updatedAt: '2006-08-15',
      episodeNumber: '52',
      type: 1,
      length: 25,
      airDate: '2002-10-06',
      rating: null,
      votes: null,
      titles: [
        { title: '心を繋ぐファイト', language: 'ja' },
        { title: 'Episode 52', language: 'en' },
        { title: 'Die Bekehrung', language: 'de' },
        { title: 'Kokoro o Tsunagu Fight', language: 'x-jat' },
      ],
    },
    {
      id: 60498,
      updatedAt: '2006-08-15',
      episodeNumber: '53',
      type: 1,
      length: 25,
      airDate: '2002-10-13',
      rating: null,
      votes: null,
      titles: [
        { title: '秘められた力', language: 'ja' },
        { title: 'Episode 53', language: 'en' },
        { title: 'Die verborgene Kraft', language: 'de' },
        { title: 'Himerareta Chikara', language: 'x-jat' },
      ],
    },
    {
      id: 60499,
      updatedAt: '2006-08-15',
      episodeNumber: '54',
      type: 1,
      length: 25,
      airDate: '2002-10-20',
      rating: null,
      votes: null,
      titles: [
        { title: '忍者ファイターを撃ち破れ!', language: 'ja' },
        { title: 'Episode 54', language: 'en' },
        { title: 'Fata Morgana', language: 'de' },
        { title: 'Ninja Fighter o Uchiyabure!', language: 'x-jat' },
      ],
    },
    {
      id: 60500,
      updatedAt: '2006-08-15',
      episodeNumber: '55',
      type: 1,
      length: 25,
      airDate: '2002-10-27',
      rating: null,
      votes: null,
      titles: [
        { title: '誇りあるギアファイト', language: 'ja' },
        { title: 'Episode 55', language: 'en' },
        { title: 'Die Erpressung', language: 'de' },
        { title: 'Hokori Aru Gear Fight', language: 'x-jat' },
      ],
    },
    {
      id: 60501,
      updatedAt: '2006-08-15',
      episodeNumber: '56',
      type: 1,
      length: 25,
      airDate: '2002-11-03',
      rating: null,
      votes: null,
      titles: [
        { title: '対決!クロウド対キョウスケ!', language: 'ja' },
        { title: 'Episode 56', language: 'en' },
        { title: 'Showdown', language: 'de' },
        { title: 'Taiketsu! Kuroudo tai Kyousuke!', language: 'x-jat' },
      ],
    },
    {
      id: 60502,
      updatedAt: '2006-08-15',
      episodeNumber: '57',
      type: 1,
      length: 25,
      airDate: '2002-11-10',
      rating: null,
      votes: null,
      titles: [
        { title: '友情のリング', language: 'ja' },
        { title: 'Episode 57', language: 'en' },
        { title: 'Claudes Geständnis', language: 'de' },
        { title: 'Yuujou no Ring', language: 'x-jat' },
      ],
    },
    {
      id: 60503,
      updatedAt: '2006-08-15',
      episodeNumber: '58',
      type: 1,
      length: 25,
      airDate: '2002-11-17',
      rating: null,
      votes: null,
      titles: [
        { title: '勝利を掴む者', language: 'ja' },
        { title: 'Episode 58', language: 'en' },
        { title: 'Ein wichtiges Training', language: 'de' },
        { title: 'Shouri o Tsukamu Mono', language: 'x-jat' },
      ],
    },
    {
      id: 60504,
      updatedAt: '2006-08-15',
      episodeNumber: '59',
      type: 1,
      length: 25,
      airDate: '2002-11-24',
      rating: null,
      votes: null,
      titles: [
        { title: '古城の対決!ジロウ対U-YA!', language: 'ja' },
        { title: 'Episode 59', language: 'en' },
        { title: 'Unter wilden Tieren', language: 'de' },
        { title: 'Kojou no Taiketsu! Jirou tai U-YA!', language: 'x-jat' },
      ],
    },
    {
      id: 60505,
      updatedAt: '2006-08-15',
      episodeNumber: '60',
      type: 1,
      length: 25,
      airDate: '2002-12-01',
      rating: null,
      votes: null,
      titles: [
        { title: '約束のファイト', language: 'ja' },
        { title: 'Episode 60', language: 'en' },
        { title: 'Die Spezialattacke', language: 'de' },
        { title: 'Yakusoku no Fight', language: 'x-jat' },
      ],
    },
    {
      id: 60506,
      updatedAt: '2006-08-15',
      episodeNumber: '61',
      type: 1,
      length: 25,
      airDate: '2002-12-08',
      rating: null,
      votes: null,
      titles: [
        { title: '友に届け!ギアの心', language: 'ja' },
        { title: 'Episode 61', language: 'en' },
        { title: 'Risiko', language: 'de' },
        { title: 'Tomo ni Todoke! Gear no Kokoro', language: 'x-jat' },
      ],
    },
    {
      id: 60507,
      updatedAt: '2006-08-15',
      episodeNumber: '62',
      type: 1,
      length: 25,
      airDate: '2002-12-15',
      rating: null,
      votes: null,
      titles: [
        { title: '黒い森のギアマスター', language: 'ja' },
        { title: 'Episode 62', language: 'en' },
        { title: 'Der lange Marsch', language: 'de' },
        { title: 'Kuroi Mori no Gear Master', language: 'x-jat' },
      ],
    },
    {
      id: 60508,
      updatedAt: '2006-08-15',
      episodeNumber: '63',
      type: 1,
      length: 25,
      airDate: '2002-12-22',
      rating: null,
      votes: null,
      titles: [
        { title: 'ガルダの名の下に', language: 'ja' },
        { title: 'Episode 63', language: 'en' },
        { title: 'Botschaft aus dem Jenseits', language: 'de' },
        { title: 'Garuda no Na no Shita ni', language: 'x-jat' },
      ],
    },
    {
      id: 60509,
      updatedAt: '2006-08-15',
      episodeNumber: '64',
      type: 1,
      length: 25,
      airDate: '2002-12-29',
      rating: null,
      votes: null,
      titles: [
        { title: '魂のギアファイト', language: 'ja' },
        { title: 'Episode 64', language: 'en' },
        { title: 'Ein ganz besonderes Match', language: 'de' },
        { title: 'Tamashii no Gear Fight', language: 'x-jat' },
      ],
    },
    {
      id: 60510,
      updatedAt: '2006-08-15',
      episodeNumber: '65',
      type: 1,
      length: 25,
      airDate: '2003-01-05',
      rating: null,
      votes: null,
      titles: [
        { title: '永遠の好敵手[ライバル]', language: 'ja' },
        { title: 'Episode 65', language: 'en' },
        { title: 'Der ewige Rivale', language: 'de' },
        { title: 'Eien no Rival', language: 'x-jat' },
      ],
    },
    {
      id: 60511,
      updatedAt: '2006-08-15',
      episodeNumber: '66',
      type: 1,
      length: 25,
      airDate: '2003-01-12',
      rating: null,
      votes: null,
      titles: [
        { title: '運命のラストファイト', language: 'ja' },
        { title: 'Episode 66', language: 'en' },
        { title: 'Der große Moment', language: 'de' },
        { title: 'Unmei no Last Fight', language: 'x-jat' },
      ],
    },
    {
      id: 60512,
      updatedAt: '2006-08-15',
      episodeNumber: '67',
      type: 1,
      length: 25,
      airDate: '2003-01-19',
      rating: null,
      votes: null,
      titles: [
        { title: 'リングを翔ける疾風[かぜ]', language: 'ja' },
        { title: 'Episode 67', language: 'en' },
        { title: 'Takeshis Mission', language: 'de' },
        { title: 'Ring o Kakeru Kaze', language: 'x-jat' },
      ],
    },
    {
      id: 60513,
      updatedAt: '2006-08-15',
      episodeNumber: '68',
      type: 1,
      length: 25,
      airDate: '2003-01-26',
      rating: null,
      votes: null,
      titles: [
        { title: '輝け!熱きギア魂!', language: 'ja' },
        { title: 'Episode 68', language: 'en' },
        { title: 'Endlich Weltmeister!', language: 'de' },
        { title: 'Kagayake! Atsuki Gear Tamashii!', language: 'x-jat' },
      ],
    },
    {
      id: 89064,
      updatedAt: '2010-11-01',
      episodeNumber: 'C3',
      type: 3,
      length: 2,
      airDate: undefined,
      rating: null,
      votes: null,
      titles: [{ title: 'German Opening', language: 'en' }],
    },
    {
      id: 124873,
      updatedAt: '2010-11-01',
      episodeNumber: 'C2',
      type: 3,
      length: 2,
      airDate: '2001-10-07',
      rating: null,
      votes: null,
      titles: [{ title: 'Ending', language: 'en' }],
    },
    {
      id: 124874,
      updatedAt: '2010-11-01',
      episodeNumber: 'C1',
      type: 3,
      length: 2,
      airDate: '2001-10-07',
      rating: null,
      votes: null,
      titles: [{ title: 'Opening', language: 'en' }],
    },
  ],
};
