module.exports = [
  {
    id: 13619,
    ageRestricted: false,
    type: 'TV Series',
    episodeCount: 10,
    startDate: '2018-07-04',
    endDate: '2018-09-05',
    titles: [],
    description: undefined,
    picture: '221819.jpg',
    ratings: {
      permanent: { score: '395', count: '43' },
      temporary: { score: undefined, count: undefined },
      review: { score: undefined, count: undefined },
    },
    related: [],
    similar: [],
    recommendations: [],
    url: undefined,
    creators: [],
    resources: [],
    tags: [],
    characters: [],
    episodes: [],
  },
  {
    id: 4597,
    ageRestricted: false,
    type: 'TV Series',
    episodeCount: 12,
    startDate: '2006-10-04',
    endDate: '2006-12-20',
    titles: [],
    description: undefined,
    picture: '131092.jpg',
    ratings: {
      permanent: { score: '827', count: '9759' },
      temporary: { score: undefined, count: undefined },
      review: { score: undefined, count: undefined },
    },
    related: [],
    similar: [],
    recommendations: [],
    url: undefined,
    creators: [],
    resources: [],
    tags: [],
    characters: [],
    episodes: [],
  },
  {
    id: 7668,
    ageRestricted: false,
    type: 'OVA',
    episodeCount: 1,
    startDate: '2010-11-22',
    endDate: '2010-11-22',
    titles: [],
    description: undefined,
    picture: '161609.jpg',
    ratings: {
      permanent: { score: '244', count: '188' },
      temporary: { score: undefined, count: undefined },
      review: { score: undefined, count: undefined },
    },
    related: [],
    similar: [],
    recommendations: [],
    url: undefined,
    creators: [],
    resources: [],
    tags: [],
    characters: [],
    episodes: [],
  },
  {
    id: 238,
    ageRestricted: false,
    type: 'TV Series',
    episodeCount: 20,
    startDate: '2000-10-07',
    endDate: '2001-03-24',
    titles: [],
    description: undefined,
    picture: '9935.jpg',
    ratings: {
      permanent: { score: '693', count: '337' },
      temporary: { score: undefined, count: undefined },
      review: { score: undefined, count: undefined },
    },
    related: [],
    similar: [],
    recommendations: [],
    url: undefined,
    creators: [],
    resources: [],
    tags: [],
    characters: [],
    episodes: [],
  },
  {
    id: 11980,
    ageRestricted: false,
    type: 'Movie',
    episodeCount: 1,
    startDate: '2017-06-17',
    endDate: '2017-06-17',
    titles: [],
    description: undefined,
    picture: '221832.jpg',
    ratings: {
      permanent: { score: '529', count: '312' },
      temporary: { score: undefined, count: undefined },
      review: { score: undefined, count: undefined },
    },
    related: [],
    similar: [],
    recommendations: [],
    url: undefined,
    creators: [],
    resources: [],
    tags: [],
    characters: [],
    episodes: [],
  },
  {
    id: 834,
    ageRestricted: false,
    type: 'TV Series',
    episodeCount: 12,
    startDate: '2003-07-13',
    endDate: '2003-09-28',
    titles: [],
    description: undefined,
    picture: '534.jpg',
    ratings: {
      permanent: { score: '432', count: '5323' },
      temporary: { score: undefined, count: undefined },
      review: { score: undefined, count: undefined },
    },
    related: [],
    similar: [],
    recommendations: [],
    url: undefined,
    creators: [],
    resources: [],
    tags: [],
    characters: [],
    episodes: [],
  },
  {
    id: 3706,
    ageRestricted: false,
    type: 'OVA',
    episodeCount: 6,
    startDate: '2005-12-09',
    endDate: '2006-06-23',
    titles: [],
    description: undefined,
    picture: '10733.jpg',
    ratings: {
      permanent: { score: '595', count: '1900' },
      temporary: { score: undefined, count: undefined },
      review: { score: undefined, count: undefined },
    },
    related: [],
    similar: [],
    recommendations: [],
    url: undefined,
    creators: [],
    resources: [],
    tags: [],
    characters: [],
    episodes: [],
  },
  {
    id: 3431,
    ageRestricted: false,
    type: 'OVA',
    episodeCount: 1,
    startDate: '2005-09-23',
    endDate: '2005-09-23',
    titles: [],
    description: undefined,
    picture: '47675.jpg',
    ratings: {
      permanent: { score: '840', count: '1450' },
      temporary: { score: undefined, count: undefined },
      review: { score: undefined, count: undefined },
    },
    related: [],
    similar: [],
    recommendations: [],
    url: undefined,
    creators: [],
    resources: [],
    tags: [],
    characters: [],
    episodes: [],
  },
  {
    id: 306,
    ageRestricted: false,
    type: 'Movie',
    episodeCount: 1,
    startDate: '1992-07-18',
    endDate: '1992-07-18',
    titles: [],
    description: undefined,
    picture: '145634.jpg',
    ratings: {
      permanent: { score: '772', count: '3820' },
      temporary: { score: undefined, count: undefined },
      review: { score: undefined, count: undefined },
    },
    related: [],
    similar: [],
    recommendations: [],
    url: undefined,
    creators: [],
    resources: [],
    tags: [],
    characters: [],
    episodes: [],
  },
  {
    id: 11255,
    ageRestricted: false,
    type: 'TV Series',
    episodeCount: 12,
    startDate: '2016-01-11',
    endDate: '2016-03-28',
    titles: [],
    description: undefined,
    picture: '180172.jpg',
    ratings: {
      permanent: { score: '368', count: '697' },
      temporary: { score: undefined, count: undefined },
      review: { score: undefined, count: undefined },
    },
    related: [],
    similar: [],
    recommendations: [],
    url: undefined,
    creators: [],
    resources: [],
    tags: [],
    characters: [],
    episodes: [],
  },
];
